import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { closeSqlServer, getSqlServerPool } from '../src/config/sqlserver.js';

type Column = { columnName: string; datatype: string; nullable?: string; maxLength?: number | null; precision?: number | null; scale?: number | null };
type ObjectRecord = { schemaName: string; objectName: string; objectType: string; columns?: Column[]; keys?: Array<{ columnName: string; constraintType: string }>; indexes?: Array<{ indexName: string; isUnique?: boolean }> };
const root = join(process.cwd(), '..', 'semantic', 'catalog');
const schema = JSON.parse(await readFile(join(root, 'schema.json'), 'utf8')) as { objects: ObjectRecord[] };
const names = ['MRP', 'MRP_TMP', 'PURCH_MRP', 'PURCH_MRP_MONTHLY', 'PURCH_MRP_NOTE', 'PURCH_MRP_OVERTIME', 'PURCH_MRP_OVERTIMEHEAD', 'PURCH_MRP_TOTAL_GROUPNAME', 'PURCH_MRP_YEAR', 'forecast'];
const candidates = names.map((name) => schema.objects.find((object) => object.schemaName === 'dbo' && object.objectName.toLowerCase() === name.toLowerCase())).filter((object): object is ObjectRecord => Boolean(object));
const quote = (value: string) => `[${value.replace(/]/g, ']]')}]`;
const qualified = (object: ObjectRecord) => `${quote(object.schemaName)}.${quote(object.objectName)}`;
const numeric = new Set(['tinyint', 'smallint', 'int', 'bigint', 'decimal', 'numeric', 'money', 'smallmoney', 'float', 'real']);
const dateNative = new Set(['date', 'datetime', 'datetime2', 'smalldatetime', 'datetimeoffset']);
function errorMeta(error: unknown, object?: string, column?: string) { const value = error as { number?: unknown; code?: unknown; name?: unknown; class?: unknown; state?: unknown; message?: unknown }; return { object, column, errorNumber: typeof value.number === 'number' ? value.number : undefined, errorCode: typeof value.code === 'string' ? value.code : undefined, errorClass: typeof value.class === 'number' ? value.class : undefined, errorState: typeof value.state === 'number' ? value.state : undefined, errorName: typeof value.name === 'string' ? value.name : 'SQL_ERROR', errorMessageClass: typeof value.message === 'string' ? value.message.split(':')[0].slice(0, 120) : 'SQL_ERROR' }; }
let pool: Awaited<ReturnType<typeof getSqlServerPool>>;
try { pool = await getSqlServerPool(); } catch (error) { const report = { generatedAt: new Date().toISOString(), status: 'DB_UNAVAILABLE', connection: errorMeta(error, 'SQLSERVER'), security: { rawRowsPersisted: false, databaseMutation: false, geminiInvolved: false }, objects: [], relationships: { mrpToMaterial: [], mrpToInventory: { status: 'NOT_VALIDATED', runtimeJoinAllowed: false }, mrpToPurchaseRequest: { status: 'NOT_VALIDATED', runtimeJoinAllowed: false } }, promotion: { entity: 'material_requirement', queryable: false, blockers: ['SQL Server connection unavailable; field evidence not refreshed'] } }; await mkdir(root, { recursive: true }); await writeFile(join(root, 'mrp-evidence.json'), `${JSON.stringify(report, null, 2)}\n`); console.log(JSON.stringify({ status: report.status, connection: report.connection }, null, 2)); process.exit(0); }
async function safeAggregate(object: ObjectRecord, column: Column) {
  const columnSql = quote(column.columnName); const objectSql = qualified(object); const base = { object: `${object.schemaName}.${object.objectName}`, column: column.columnName, datatype: column.datatype };
  try {
    const select = [`COUNT_BIG(*) AS row_count`, `SUM(CASE WHEN ${columnSql} IS NULL THEN 1 ELSE 0 END) AS null_count`, `COUNT(DISTINCT ${columnSql}) AS distinct_count`];
    if (numeric.has(column.datatype.toLowerCase())) { select.push(`MIN(${columnSql}) AS minValue`, `MAX(${columnSql}) AS maxValue`); }
    if (dateNative.has(column.datatype.toLowerCase())) { select.push(`MIN(${columnSql}) AS minDate`, `MAX(${columnSql}) AS maxDate`); }
    if (/^varchar$|^nvarchar$|^char$|^nchar$/i.test(column.datatype) && /date/i.test(column.columnName)) { select.push(`SUM(CASE WHEN TRY_CONVERT(date, ${columnSql}, 23) IS NOT NULL OR TRY_CONVERT(date, ${columnSql}, 103) IS NOT NULL OR TRY_CONVERT(date, ${columnSql}, 112) IS NOT NULL THEN 1 ELSE 0 END) AS parseableDateCount`); }
    const row = (await pool.request().query(`SELECT ${select.join(', ')} FROM ${objectSql}`)).recordset[0] as Record<string, unknown>;
    return { ...base, status: 'AVAILABLE', aggregates: { rowCount: Number(row.row_count ?? 0), nullCount: Number(row.null_count ?? 0), distinctCount: Number(row.distinct_count ?? 0), ...(row.minValue === undefined ? {} : { minValuePresent: row.minValue !== null }), ...(row.maxValue === undefined ? {} : { maxValuePresent: row.maxValue !== null }), ...(row.minDate === undefined ? {} : { minDatePresent: row.minDate !== null }), ...(row.maxDate === undefined ? {} : { maxDatePresent: row.maxDate !== null }), ...(row.parseableDateCount === undefined ? {} : { parseableDateCount: Number(row.parseableDateCount ?? 0) }) } };
  } catch (error) { return { ...base, status: 'ERROR', error: errorMeta(error, base.object, column.columnName) }; }
}
async function objectMeta(object: ObjectRecord) { try { const row = (await pool.request().input('schemaName', object.schemaName).input('objectName', object.objectName).query(`SELECT o.object_id AS objectId,o.type_desc AS typeDescription,SCHEMA_NAME(o.schema_id) AS schemaName,o.name AS objectName FROM sys.objects o WHERE o.schema_id=SCHEMA_ID(@schemaName) AND o.name=@objectName`)).recordset[0] as Record<string, unknown> | undefined; return row ? { status: 'AVAILABLE', objectId: row.objectId, type: row.typeDescription } : { status: 'NOT_FOUND', object: `${object.schemaName}.${object.objectName}` }; } catch (error) { return { status: 'ERROR', error: errorMeta(error, `${object.schemaName}.${object.objectName}`) }; } }
async function definitions() { try { const rows = await pool.request().query<{ objectName: string; typeDescription: string; definition: string }>(`SELECT o.name AS objectName,o.type_desc AS typeDescription,m.definition FROM sys.sql_modules m JOIN sys.objects o ON o.object_id=m.object_id WHERE m.definition LIKE '%MRP%' OR m.definition LIKE '%PURC_PURCHREQUEST_TEMP%' OR m.definition LIKE '%PURC_PURCHASE_REQUEST%'`); return rows.recordset.map((row: { objectName: string; typeDescription: string; definition: string }) => ({ objectName: row.objectName, type: row.typeDescription, references: [...new Set(['MRP', 'QtyPR', 'PURC_PURCHREQUEST_TEMP', 'PURC_PURCHASE_REQUEST', 'Status_Info', 'Approval_Info', 'Dept', 'Requestor'].filter((term) => row.definition.toLowerCase().includes(term.toLowerCase())))] })); } catch (error) { return { status: 'ERROR', error: errorMeta(error, 'sys.sql_modules') }; } }
async function materialRelationship() { const targets = ['MAS_MAPPINGMATERIAL', 'PURC_MATCATALOG', 'PURC_MATCATALOG_TEMP', 'MAS_MATERIAL']; const source = '[dbo].[MRP]'; const results = []; for (const target of targets) { try { const query = `WITH s AS (SELECT TOP (@limit) NULLIF(LTRIM(RTRIM(CONVERT(nvarchar(255),[MaterialId]))),'') AS value FROM ${source} WHERE [MaterialId] IS NOT NULL), t AS (SELECT DISTINCT NULLIF(LTRIM(RTRIM(CONVERT(nvarchar(255),[MaterialId]))),'') AS value FROM [dbo].${quote(target)} WHERE [MaterialId] IS NOT NULL), m AS (SELECT CASE WHEN t.value IS NULL THEN 0 ELSE 1 END AS matched FROM s LEFT JOIN t ON t.value=s.value) SELECT COUNT_BIG(*) AS sampled,SUM(matched) AS matched FROM m`; const row = (await pool.request().input('limit', 10000).query(query)).recordset[0] as Record<string, unknown>; const sampled = Number(row.sampled ?? 0); const matched = Number(row.matched ?? 0); results.push({ target: `dbo.${target}.MaterialId`, status: 'AVAILABLE', sampled, matched, unmatched: sampled - matched, matchRate: sampled ? matched / sampled : 0, confidence: sampled && matched / sampled >= 0.99 ? 'CONFIRMED_BY_DATA' : 'PROBABLE' }); } catch (error) { results.push({ target: `dbo.${target}.MaterialId`, status: 'ERROR', error: errorMeta(error, `dbo.${target}`, 'MaterialId') }); } } return results; }
try { const fieldPattern = /^(MRPNo|MRPDate|MaterialId|Qty$|Qty[1-5]|QtyPR|Status$|Status_info|Status_Date|.*Date$|.*_Date$)$/i; const report = { generatedAt: new Date().toISOString(), security: { rawRowsPersisted: false, databaseMutation: false, geminiInvolved: false }, objects: await Promise.all(candidates.map(async (object) => ({ schema: object.schemaName, object: object.objectName, type: object.objectType, metadata: await objectMeta(object), columns: (object.columns ?? []).filter((column) => fieldPattern.test(column.columnName)), primaryKeys: (object.keys ?? []).filter((key) => key.constraintType === 'PRIMARY KEY').map((key) => key.columnName), indexes: object.indexes ?? [], aggregates: await Promise.all((object.columns ?? []).filter((column) => fieldPattern.test(column.columnName)).map((column) => safeAggregate(object, column))) }))), codeEvidence: await definitions(), relationships: { mrpToMaterial: await materialRelationship(), mrpToInventory: { status: 'NOT_VALIDATED', runtimeJoinAllowed: false }, mrpToPurchaseRequest: { status: 'NOT_VALIDATED', runtimeJoinAllowed: false } }, promotion: { entity: 'material_requirement', queryable: false, blockers: ['Quantity semantics unresolved', 'MRPDate varchar/date meaning unresolved', 'Status meaning unresolved', 'MRP-to-PR relationship unresolved', 'MRP-to-inventory relationship unresolved'] } };
await mkdir(root, { recursive: true }); await writeFile(join(root, 'mrp-evidence.json'), `${JSON.stringify(report, null, 2)}\n`); console.log(JSON.stringify({ objects: report.objects.length, codeEvidence: Array.isArray(report.codeEvidence) ? report.codeEvidence.length : 0, relationships: report.relationships.mrpToMaterial.length, queryable: report.promotion.queryable }, null, 2)); } finally { await closeSqlServer(); }
