import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { getSqlServerPool, closeSqlServer } from '../src/config/sqlserver.js';

const root = join(process.cwd(), '..', 'semantic', 'catalog');
try {
  const pool = await getSqlServerPool();
  const [objects, columns, keys, relationships, indexes, dependencies, procedures] = await Promise.all([
    pool.request().query(`SELECT s.name AS schemaName, o.name AS objectName, CASE WHEN o.type='U' THEN 'TABLE' WHEN o.type='V' THEN 'VIEW' ELSE o.type_desc END AS objectType FROM sys.objects o JOIN sys.schemas s ON s.schema_id=o.schema_id WHERE o.type IN ('U','V') ORDER BY s.name,o.name`),
    pool.request().query(`SELECT TABLE_SCHEMA AS schemaName,TABLE_NAME AS objectName,COLUMN_NAME AS columnName,DATA_TYPE AS datatype,CHARACTER_MAXIMUM_LENGTH AS maxLength,NUMERIC_PRECISION AS precision,NUMERIC_SCALE AS scale,IS_NULLABLE AS nullable,COLUMNPROPERTY(OBJECT_ID(TABLE_SCHEMA+'.'+TABLE_NAME),COLUMN_NAME,'IsComputed') AS computed FROM INFORMATION_SCHEMA.COLUMNS ORDER BY TABLE_SCHEMA,TABLE_NAME,ORDINAL_POSITION`),
    pool.request().query(`SELECT s.name AS schemaName,o.name AS objectName,c.name AS columnName,tc.CONSTRAINT_TYPE AS constraintType FROM sys.objects o JOIN sys.schemas s ON s.schema_id=o.schema_id JOIN sys.index_columns ic ON ic.object_id=o.object_id JOIN sys.columns c ON c.object_id=ic.object_id AND c.column_id=ic.column_id JOIN sys.key_constraints kc ON kc.parent_object_id=o.object_id AND kc.unique_index_id=ic.index_id JOIN INFORMATION_SCHEMA.TABLE_CONSTRAINTS tc ON tc.CONSTRAINT_NAME=kc.name AND tc.TABLE_SCHEMA=s.name WHERE o.type='U'`),
    pool.request().query(`SELECT OBJECT_SCHEMA_NAME(fkc.parent_object_id) AS fromSchema,OBJECT_NAME(fkc.parent_object_id) AS fromObject,pc.name AS fromColumn,OBJECT_SCHEMA_NAME(fkc.referenced_object_id) AS toSchema,OBJECT_NAME(fkc.referenced_object_id) AS toObject,rc.name AS toColumn,'FOREIGN_KEY' AS evidence,'CONFIRMED_BY_CODE' AS confidence FROM sys.foreign_key_columns fkc JOIN sys.columns pc ON pc.object_id=fkc.parent_object_id AND pc.column_id=fkc.parent_column_id JOIN sys.columns rc ON rc.object_id=fkc.referenced_object_id AND rc.column_id=fkc.referenced_column_id`),
    pool.request().query(`SELECT s.name AS schemaName,o.name AS objectName,i.name AS indexName,i.is_unique AS isUnique,i.type_desc AS indexType FROM sys.indexes i JOIN sys.objects o ON o.object_id=i.object_id JOIN sys.schemas s ON s.schema_id=o.schema_id WHERE o.type IN ('U','V') AND i.name IS NOT NULL`),
    pool.request().query(`SELECT OBJECT_SCHEMA_NAME(referencing_id) AS fromSchema,OBJECT_NAME(referencing_id) AS fromObject,referenced_schema_name AS toSchema,referenced_entity_name AS toObject FROM sys.sql_expression_dependencies WHERE referenced_entity_name IS NOT NULL`),
    pool.request().query(`SELECT s.name AS schemaName,o.name AS objectName FROM sys.objects o JOIN sys.schemas s ON s.schema_id=o.schema_id WHERE o.type IN ('P','PC')`)
  ]);
  await mkdir(root, { recursive: true });
  const catalog = { generatedAt: new Date().toISOString(), objects: objects.recordset.map((object) => ({ ...object, columns: columns.recordset.filter((column) => column.schemaName === object.schemaName && column.objectName === object.objectName), keys: keys.recordset.filter((key) => key.schemaName === object.schemaName && key.objectName === object.objectName), indexes: indexes.recordset.filter((index) => index.schemaName === object.schemaName && index.objectName === object.objectName) })), relationships: relationships.recordset, dependencies: dependencies.recordset, storedProcedures: procedures.recordset };
  const coverage = { generatedAt: catalog.generatedAt, discovered: { objects: catalog.objects.length, tables: catalog.objects.filter((object) => object.objectType === 'TABLE').length, views: catalog.objects.filter((object) => object.objectType === 'VIEW').length, columns: columns.recordset.length }, classified: { objects: 0, unknown: catalog.objects.length }, semantic: { entities: 0, confirmed: 0, probable: 0, unknown: 0, blocked: 0 }, relationships: { fkConfirmed: relationships.recordset.length, confirmedByData: 0, probable: 0, unknown: 0 }, policy: { allowed: 0, restricted: 0, blocked: 0, unclassified: catalog.objects.length } };
  await writeFile(join(root, 'schema.json'), JSON.stringify(catalog, null, 2)); await writeFile(join(root, 'coverage.json'), JSON.stringify(coverage, null, 2)); console.log(JSON.stringify(coverage, null, 2));
} finally { await closeSqlServer(); }
