import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { join } from 'node:path';
import { z } from 'zod';
import { refreshPending } from '../src/semantic/review.js';

const root = join(process.cwd(), '..', 'semantic', 'catalog');
const docsRoot = join(process.cwd(), '..', 'docs');
const confidence = ['CONFIRMED_BY_SCHEMA', 'CONFIRMED_BY_CODE', 'CONFIRMED_BY_DATA', 'PROBABLE', 'UNKNOWN', 'BLOCKED'] as const;
const domains = ['customer', 'sales', 'purchasing', 'purchase_request', 'purchase_order', 'inventory', 'warehouse', 'delivery', 'production', 'machine', 'maintenance', 'quality', 'finance', 'hr', 'material', 'supplier', 'master_data', 'unknown'] as const;
type Confidence = typeof confidence[number];
type Domain = typeof domains[number];
type ObjectRecord = { schemaName: string; objectName: string; objectType: string; columns?: Array<{ columnName: string; datatype: string; nullable?: string; computed?: number }>; keys?: Array<{ columnName: string; constraintType: string }>; indexes?: Array<{ isUnique?: boolean }> };
type Seed = { version?: number; entities: Array<Record<string, any>> };

const schema = z.object({ generatedAt: z.string().optional(), objects: z.array(z.record(z.any())), relationships: z.array(z.record(z.any())).default([]), dependencies: z.array(z.record(z.any())).default([]), storedProcedures: z.array(z.record(z.any())).default([]) });
const seedSchema = z.object({ version: z.number().optional(), entities: z.array(z.record(z.any())) });

function textOf(object: ObjectRecord) { return [object.objectName, ...(object.columns ?? []).map((column) => column.columnName)].join(' ').toLowerCase(); }
function classify(object: ObjectRecord): { domain: Domain; confidence: Confidence; evidence: string[] } {
  const text = textOf(object); const name = object.objectName.toLowerCase();
  if (/salary|payroll|bank|rekening|password|credential|security|user_login|audit_log/.test(text)) return { domain: /salary|payroll|employee|pegawai|hr/.test(text) ? 'hr' : 'finance', confidence: 'UNKNOWN', evidence: ['sensitive-name-pattern'] };
  const rules: Array<[Domain, RegExp, string]> = [['customer', /customer|pelanggan|cust/, 'customer-name-or-column'], ['purchase_request', /purchase.?request|permintaan|\bpr\b|prdetail|prheader/, 'purchase-request-name-or-column'], ['purchase_order', /purchase.?order|purch.?order|\bpo\b|podetail|pov/, 'purchase-order-name-or-column'], ['purchasing', /purc|purch|procure|vendor|supplier|bid|rfq/, 'purchasing-name-or-column'], ['sales', /sales|sls|order|so_/, 'sales-name-or-column'], ['delivery', /delivery|deliver|shipment|pengiriman|sj|do_/, 'delivery-name-or-column'], ['inventory', /stock|stok|inventory|persediaan|wms|warehouse|gudang|mutation/, 'inventory-name-or-column'], ['material', /material|matcatalog|part_number|partnumber|item/, 'material-name-or-column'], ['production', /produksi|production|furnace|triming|planning|casting|mesin_produksi/, 'production-name-or-column'], ['machine', /machine|mesin|equipment|asset|aset/, 'machine-name-or-column'], ['maintenance', /maintenance|repair|service|pemeliharaan/, 'maintenance-name-or-column'], ['quality', /quality|qc|reject|inspection|inspeksi/, 'quality-name-or-column'], ['finance', /finance|invoice|faktur|payment|accounting|journal/, 'finance-name-or-column'], ['hr', /employee|pegawai|karyawan|personnel|absen|attendance/, 'hr-name-or-column'], ['supplier', /supplier|vendor/, 'supplier-name-or-column'], ['master_data', /master|catalog|katalog|reference|lookup/, 'master-name-or-column']];
  const match = rules.find(([, pattern]) => pattern.test(text));
  if (match) return { domain: match[0], confidence: match[0] === 'master_data' ? 'PROBABLE' : 'UNKNOWN', evidence: [match[2]] };
  return { domain: 'unknown', confidence: 'UNKNOWN', evidence: [] };
}
function policy(object: ObjectRecord) { const text = textOf(object); if (/salary|payroll|bank|rekening|password|credential|token|secret|security|user_login|audit_log|birth|dob|ktp|npwp/.test(text)) return { classification: 'RESTRICTED', reason: 'sensitive-name-pattern' }; if (/employee|pegawai|karyawan|hr|finance|invoice|payment|faktur/.test(text)) return { classification: 'CONFIDENTIAL', reason: 'sensitive-domain-pattern' }; if (object.objectType === 'VIEW' || /customer|sales|delivery|material|stock|inventory/.test(text)) return { classification: 'INTERNAL', reason: 'approved-business-domain-pattern' }; return { classification: 'UNCLASSIFIED', reason: 'no-approved-policy-evidence' }; }
function aliases(entity: string) { return { customer: ['customer', 'pelanggan'], material: ['material', 'part', 'barang'], supplier: ['supplier', 'vendor'], purchase_request: ['PR', 'purchase request', 'permintaan pembelian'], purchase_order: ['PO', 'purchase order'], sales_order: ['SO', 'sales order', 'order'], delivery: ['delivery', 'pengiriman', 'DO'], inventory: ['stock', 'stok', 'persediaan'], machine: ['machine', 'mesin'], production: ['production', 'produksi'] }[entity] ?? [entity]; }
function candidateFields(object: ObjectRecord, classification: string) { return Object.fromEntries((object.columns ?? []).slice(0, 40).map((column) => [column.columnName.toLowerCase(), { physicalObject: `dbo.${object.objectName}`, physicalColumn: column.columnName, datatype: column.datatype, aliases: [column.columnName], confidence: 'UNKNOWN', classification }])); }

const loadedSchema = schema.parse(JSON.parse(await readFile(join(root, 'schema.json'), 'utf8'))); const seed = seedSchema.parse(JSON.parse(await readFile(join(root, 'semantic.json'), 'utf8'))); const profile = JSON.parse(await readFile(join(root, 'profile.json'), 'utf8').catch(() => '{}')) as { statistics?: Array<Record<string, any>>; summary?: Record<string, unknown> }; const validation = JSON.parse(await readFile(join(root, 'relationship-validation.json'), 'utf8').catch(() => '{"checks":[]}')) as { checks?: Array<Record<string, any>> }; const approved = JSON.parse(await readFile(join(process.cwd(), '..', 'semantic', 'review', 'approved.json'), 'utf8').catch(() => '[]')) as Array<Record<string, any>>; const mrpApproved = JSON.parse(await readFile(join(process.cwd(), '..', 'semantic', 'review', 'mrp-approved.json'), 'utf8').catch(() => '[]')) as Array<Record<string, any>>; await refreshPending(); const objects = loadedSchema.objects as unknown as ObjectRecord[]; const seedObjects = new Set(seed.entities.flatMap((entity) => Object.values(entity.fields ?? {}).map((field: any) => field.physicalObject)).filter(Boolean));
const sourceInvestigation = JSON.parse(await readFile(join(root, 'pr-source-investigation.json'), 'utf8').catch(() => '{"roleAssessment":{"authoritative":{"status":"NOT_CONFIRMED"}}}')) as { roleAssessment?: { authoritative?: { status?: string; source?: string | null } } }; const prSourceAuthoritative = sourceInvestigation.roleAssessment?.authoritative?.status === 'CONFIRMED' && Boolean(sourceInvestigation.roleAssessment.authoritative.source);
const classifications = objects.map((object) => ({ object, ...classify(object), policy: policy(object) }));
const entityNames = new Set(seed.entities.map((entity) => String(entity.entity))); const candidateNames = ['customer', 'material', 'supplier', 'purchase_request', 'purchase_order', 'sales_order', 'delivery', 'inventory', 'machine', 'production'];
const enrichedEntities = [...seed.entities];
for (const entityName of candidateNames) {
  if (entityNames.has(entityName)) continue;
  const matches = classifications.filter((item) => item.domain === entityName || (entityName === 'purchase_request' && item.domain === 'purchasing') || (entityName === 'purchase_order' && item.domain === 'purchasing')).slice(0, 20);
  if (!matches.length) continue;
  enrichedEntities.push({ entity: entityName, aliases: aliases(entityName), domain: entityName, confidence: 'UNKNOWN', queryable: false, physicalObjects: matches.map((item) => `dbo.${item.object.objectName}`), fields: Object.fromEntries(matches.slice(0, 3).flatMap((item) => Object.entries(candidateFields(item.object, item.policy.classification === 'UNCLASSIFIED' ? 'UNCLASSIFIED' : item.policy.classification)))) });
}
const prCheck = (from: string, to: string) => validation.checks?.find((check) => check.from === from && check.to === to); const prHeaderObject = 'dbo.PURC_PURCHREQUEST_HED'; const prDetailObject = 'dbo.PRDetail'; const prMaterialJoin = prCheck('dbo.PRDetail.MaterialID', 'dbo.PURC_MATCATALOG.Materialid'); const prHeaderDetailJoin = prCheck('dbo.PRDetail.PRNo', 'dbo.PURC_PURCHREQUEST_HED.PRNo'); const prSeed = enrichedEntities.find((entity: any) => entity.entity === 'purchase_request') as any; if (prSeed) { prSeed.promotion = { header: prHeaderObject, detail: prDetailObject, profileEvidence: profile.statistics?.filter((item) => item.object === 'PURC_PURCHREQUEST_HED' || item.object === 'PRDetail').length ?? 0, relationshipEvidence: validation.checks?.filter((check) => String(check.from).includes('PRDetail') || String(check.to).includes('PRDetail')).length ?? 0, blockers: ['quantity semantics require approved evidence', 'date semantics require approved evidence', 'status semantics require approved evidence', ...(!prHeaderDetailJoin || prHeaderDetailJoin.confidence !== 'CONFIRMED_BY_DATA' ? ['header/detail relationship not CONFIRMED_BY_DATA'] : []), ...(!prMaterialJoin || prMaterialJoin.confidence !== 'CONFIRMED_BY_DATA' ? ['material relationship not CONFIRMED_BY_DATA'] : [])] }; prSeed.queryable = prSeed.promotion.blockers.length === 0; }
const pr = enrichedEntities.find((entity: any) => entity.entity === 'purchase_request') as any; if (pr) { const fieldMap: Record<string, { physicalObject: string; physicalColumn: string; datatype: string }> = { pr_number: { physicalObject: 'dbo.PR', physicalColumn: 'PRNo', datatype: 'varchar' }, request_date: { physicalObject: 'dbo.PR', physicalColumn: 'PRDate', datatype: 'date' }, quantity: { physicalObject: 'dbo.PRDetail', physicalColumn: 'PRQty', datatype: 'numeric' }, material_description: { physicalObject: 'dbo.PRDetail', physicalColumn: 'Material Description', datatype: 'nvarchar' } }; for (const [fieldName, source] of Object.entries(fieldMap)) { const approvals = approved.filter((item) => item.entity === 'purchase_request' && item.semanticField === fieldName && item.confidence === 'CONFIRMED_BY_HUMAN'); if (!approvals.length) continue; const primary = approvals.find((item) => item.physicalSource === source.physicalObject + '.' + source.physicalColumn) ?? approvals[0]; const existing = pr.fields?.[fieldName] ?? {}; const physicalSources = approvals.map((item) => ({ physicalObject: item.physicalSource.split('.').slice(0, -1).join('.'), physicalColumn: item.physicalSource.split('.').at(-1)!.replace(/^\[|\]$/g, ''), confidence: 'CONFIRMED_BY_HUMAN', evidence: [...(item.evidence ?? []), 'HUMAN_APPROVAL'] })); pr.fields[fieldName] = { ...existing, ...source, physicalObject: primary.physicalSource.split('.').slice(0, -1).join('.'), physicalColumn: primary.physicalSource.split('.').at(-1)!.replace(/^\[|\]$/g, ''), aliases: existing.aliases ?? [fieldName], classification: existing.classification ?? 'INTERNAL', confidence: 'CONFIRMED_BY_HUMAN', queryable: prSourceAuthoritative, sourceStatus: prSourceAuthoritative ? 'AUTHORITATIVE' : 'LEGACY_OR_ALTERNATE', physicalSources, evidence: [...(existing.evidence ?? []), ...physicalSources.flatMap((item) => item.evidence), primary.approvalReason ?? ''] }; } const relationshipApproval = approved.find((item) => item.reviewId === 'pr-header-detail-v1' && item.confidence === 'CONFIRMED_BY_HUMAN'); if (relationshipApproval) { pr.joins = [{ from: 'dbo.PR.PRNo', to: 'dbo.PRDetail.PRNo', confidence: 'CONFIRMED_BY_HUMAN', dataIntegrity: relationshipApproval.dataIntegrity ?? 0.9858056777 }]; } const minimum = ['pr_number', 'material_description', 'quantity']; pr.queryable = prSourceAuthoritative && minimum.every((field) => pr.fields?.[field]?.confidence === 'CONFIRMED_BY_HUMAN') && Boolean(relationshipApproval); pr.fieldQueryability = Object.fromEntries(Object.keys(fieldMap).map((field) => [field, pr.fields?.[field]?.queryable === true])); }
const finalRoleApproved = approved.find((item) => item.reviewId === 'pr-source-final-v1' && item.confidence === 'CONFIRMED_BY_HUMAN'); const workflowRoleApproved = approved.find((item) => item.reviewId === 'pr-source-workflow-v1' && item.confidence === 'CONFIRMED_BY_HUMAN'); if (pr) { const finalFields: Record<string, { physicalColumn: string; datatype: string; reviewId: string }> = { pr_number: { physicalColumn: 'PRNo', datatype: 'char', reviewId: 'pr-final-number-v1' }, quantity: { physicalColumn: 'Qty', datatype: 'numeric', reviewId: 'pr-final-quantity-v1' }, specification: { physicalColumn: 'Specification', datatype: 'varchar', reviewId: 'pr-final-specification-v1' }, brand: { physicalColumn: 'Brand', datatype: 'varchar', reviewId: 'pr-final-brand-v1' }, material_code: { physicalColumn: 'MaterialId', datatype: 'char', reviewId: 'pr-final-material-code-v1' } }; const workflowFields: Record<string, { physicalColumn: string; datatype: string; reviewId?: string }> = { requester: { physicalColumn: 'Requestor', datatype: 'nchar' }, department: { physicalColumn: 'Dept', datatype: 'nchar' }, approval_status: { physicalColumn: 'Approval', datatype: 'nchar' } }; for (const [fieldName, source] of Object.entries(finalFields)) { const approval = approved.find((item) => item.reviewId === source.reviewId && item.confidence === 'CONFIRMED_BY_HUMAN'); if (!approval || !finalRoleApproved) continue; pr.fields[fieldName] = { ...(pr.fields?.[fieldName] ?? {}), physicalObject: 'dbo.PURC_PURCHASE_REQUEST', physicalColumn: source.physicalColumn, datatype: source.datatype, aliases: [fieldName], classification: 'INTERNAL', confidence: 'CONFIRMED_BY_HUMAN', sourceRole: 'AUTHORITATIVE_FINAL', sourceConfidence: 'CONFIRMED_BY_HUMAN', sourceStatus: 'AUTHORITATIVE', queryable: true, evidence: [...(approval.evidence ?? []), 'HUMAN_APPROVAL', finalRoleApproved.approvalReason ?? ''] }; } for (const [fieldName, source] of Object.entries(workflowFields)) { if (!workflowRoleApproved) continue; pr.fields[fieldName] = { ...(pr.fields?.[fieldName] ?? {}), physicalObject: 'dbo.PURC_PURCHREQUEST_TEMP', physicalColumn: source.physicalColumn, datatype: source.datatype, aliases: [fieldName], classification: 'INTERNAL', confidence: 'CONFIRMED_BY_HUMAN', sourceRole: 'AUTHORITATIVE_WORKFLOW', sourceConfidence: 'CONFIRMED_BY_HUMAN', sourceStatus: 'AUTHORITATIVE', queryable: true, evidence: ['workflow source role approval', workflowRoleApproved.approvalReason ?? ''] }; } const targetFields = ['pr_number', 'quantity', 'specification', 'brand']; pr.fieldQueryability = { ...(pr.fieldQueryability ?? {}), ...Object.fromEntries(targetFields.map((field) => [field, pr.fields?.[field]?.queryable === true])) }; }
const tempRoleApproved = approved.find((item) => item.reviewId === 'pr-source-workflow-v1' && item.confidence === 'CONFIRMED_BY_HUMAN'); const tempFieldMap: Record<string, { physicalColumn: string; datatype: string; reviewId: string }> = { pr_number: { physicalColumn: 'PRNo', datatype: 'varchar', reviewId: 'pr-temp-number-v1' }, material_description: { physicalColumn: 'MaterialName', datatype: 'varchar', reviewId: 'pr-temp-description-v1' }, quantity: { physicalColumn: 'Qty', datatype: 'numeric', reviewId: 'pr-temp-quantity-v1' }, material_code: { physicalColumn: 'MaterialId', datatype: 'nchar', reviewId: 'pr-temp-material-code-v1' } }; if (pr && tempRoleApproved) { for (const [fieldName, source] of Object.entries(tempFieldMap)) { const approval = approved.find((item) => item.reviewId === source.reviewId && item.confidence === 'CONFIRMED_BY_HUMAN'); if (!approval) continue; pr.fields[fieldName] = { ...(pr.fields?.[fieldName] ?? {}), physicalObject: 'dbo.PURC_PURCHREQUEST_TEMP', physicalColumn: source.physicalColumn, datatype: source.datatype, aliases: [fieldName], classification: 'INTERNAL', confidence: 'CONFIRMED_BY_HUMAN', sourceRole: 'AUTHORITATIVE_WORKFLOW', sourceConfidence: 'CONFIRMED_BY_HUMAN', sourceStatus: 'AUTHORITATIVE', queryable: true, evidence: [...(approval.evidence ?? []), 'HUMAN_APPROVAL', tempRoleApproved.approvalReason ?? ''] }; } const targetFields = ['pr_number', 'material_description', 'quantity']; pr.fieldQueryability = { ...(pr.fieldQueryability ?? {}), ...Object.fromEntries(targetFields.map((field) => [field, pr.fields?.[field]?.queryable === true])) }; pr.queryable = targetFields.every((field) => pr.fields?.[field]?.queryable === true); }
const mrp = enrichedEntities.find((entity: any) => entity.entity === 'material_requirement') as any;
if (mrp) for (const approval of mrpApproved.filter((item) => item.confidence === 'CONFIRMED_BY_HUMAN' && item.decision !== 'REJECTED')) { const field = mrp.fields?.[approval.semanticField]; if (!field || approval.physicalSource !== field.physicalObject + '.' + field.physicalColumn) continue; field.confidence = 'CONFIRMED_BY_HUMAN'; field.queryable = approval.semanticField === 'mrp_created_date' ? false : approval.semanticField === 'pr_created_quantity' ? false : true; field.evidence = [...(field.evidence ?? []), 'BUSINESS_OWNER_CONFIRMATION', approval.reason ?? '']; if (approval.enumMapping) field.enumMapping = approval.enumMapping; mrp.fieldQueryability = { ...(mrp.fieldQueryability ?? {}), [approval.semanticField]: field.queryable }; }
if (mrp) mrp.queryable = Object.values(mrp.fields ?? {}).some((field: any) => field.queryable === true);
const semantic = { ...seed, version: (seed.version ?? 1) + 1, generatedAt: new Date().toISOString(), profileEvidence: profile.summary ?? null, relationshipEvidence: validation.checks ?? [], humanApprovals: [...approved, ...mrpApproved].map((item) => ({ reviewId: item.reviewId, entity: item.entity ?? 'material_requirement', semanticField: item.semanticField, confidence: item.confidence, approvedAt: item.approvedAt })), entities: enrichedEntities };
const mappedObjects = new Set(enrichedEntities.flatMap((entity: any) => [...Object.values(entity.fields ?? {}), ...(entity.physicalObjects ?? [])].map((field: any) => typeof field === 'string' ? field : field.physicalObject)).filter(Boolean));
const domainReport: Record<string, any> = {}; for (const domain of domains) { const subset = classifications.filter((item) => item.domain === domain); domainReport[domain] = { objects: subset.length, mapped: subset.filter((item) => mappedObjects.has(`dbo.${item.object.objectName}`)).length, queryable: enrichedEntities.filter((entity: any) => entity.domain === domain && entity.queryable).length, unknown: subset.filter((item) => item.confidence === 'UNKNOWN').length }; }
const unknown = classifications.filter((item) => item.domain === 'unknown' || item.confidence === 'UNKNOWN').map((item) => ({ schema: item.object.schemaName, objectName: item.object.objectName, objectType: item.object.objectType, domain: item.domain, confidence: item.confidence, policy: item.policy.classification, evidence: item.evidence, priority: (item.object.keys?.length ?? 0) + (loadedSchema.dependencies.filter((dependency: any) => dependency.toObject === item.object.objectName || dependency.fromObject === item.object.objectName).length) * 2 + (item.object.columns?.length ?? 0) / 100 })).sort((a, b) => b.priority - a.priority);
const fields = enrichedEntities.flatMap((entity: any) => Object.values(entity.fields ?? {})); const coverage = { generatedAt: semantic.generatedAt, discovered: { objects: objects.length, tables: objects.filter((object) => object.objectType === 'TABLE').length, views: objects.filter((object) => object.objectType === 'VIEW').length, columns: objects.reduce((sum, object) => sum + (object.columns?.length ?? 0), 0) }, classified: { objects: classifications.filter((item) => item.domain !== 'unknown').length, unknown: classifications.filter((item) => item.domain === 'unknown').length }, mapped: { objects: objects.filter((object) => mappedObjects.has(`dbo.${object.objectName}`)).length, queryable: enrichedEntities.filter((entity: any) => entity.queryable).length }, semantic: { entities: enrichedEntities.length, confirmed: fields.filter((field: any) => field.confidence === 'CONFIRMED_BY_CODE' || field.confidence === 'CONFIRMED_BY_DATA' || field.confidence === 'CONFIRMED_BY_SCHEMA').length, probable: fields.filter((field: any) => field.confidence === 'PROBABLE').length, unknown: fields.filter((field: any) => field.confidence === 'UNKNOWN').length, blocked: fields.filter((field: any) => field.confidence === 'BLOCKED').length }, relationships: { fkConfirmed: loadedSchema.relationships.filter((relationship: any) => relationship.confidence === 'CONFIRMED_BY_SCHEMA' || relationship.confidence === 'CONFIRMED_BY_CODE').length, confirmedByData: loadedSchema.relationships.filter((relationship: any) => relationship.confidence === 'CONFIRMED_BY_DATA').length, probable: loadedSchema.relationships.filter((relationship: any) => relationship.confidence === 'PROBABLE').length, unknown: loadedSchema.relationships.filter((relationship: any) => relationship.confidence === 'UNKNOWN').length }, policy: { allowed: classifications.filter((item) => item.policy.classification === 'PUBLIC_INTERNAL' || item.policy.classification === 'INTERNAL').length, restricted: classifications.filter((item) => item.policy.classification === 'CONFIDENTIAL' || item.policy.classification === 'RESTRICTED').length, blocked: classifications.filter((item) => item.policy.classification === 'BLOCKED').length, unclassified: classifications.filter((item) => item.policy.classification === 'UNCLASSIFIED').length } };
const prCandidates = classifications.filter((item) => item.domain === 'purchase_request' || item.domain === 'purchasing').filter((item) => /pr|request|permintaan|purchase|detail|header/i.test(textOf(item.object))).map((item) => ({ objectName: `dbo.${item.object.objectName}`, objectType: item.object.objectType, columns: (item.object.columns ?? []).map((column) => column.columnName).filter((column) => /no|number|nomor|date|tanggal|material|item|qty|quantity|status|approve|department|depart|request|user|peminta/i.test(column)), confidence: item.confidence, evidence: item.evidence }));
const prReport = { generatedAt: semantic.generatedAt, status: prCandidates.some((candidate) => candidate.columns.some((column) => /pr|nomor|number|no/i.test(column)) && candidate.columns.some((column) => /qty|quantity/i.test(column))) ? 'MAPPING_REVIEW_REQUIRED' : 'MAPPING_NOT_FOUND', headerCandidates: prCandidates.filter((candidate) => /hed|header/i.test(candidate.objectName)), detailCandidates: prCandidates.filter((candidate) => /det|detail/i.test(candidate.objectName)), candidates: prCandidates.slice(0, 100), missingEvidence: ['validated PR header/detail pair', 'PR number field', 'material join to PURC_MATCATALOG.Materialid', 'quantity/date/status semantics', 'bounded match-rate validation'] };
const before = { entities: seed.entities.length, queryable: seed.entities.filter((entity: any) => entity.queryable).length, confirmed: seed.entities.flatMap((entity: any) => Object.values(entity.fields ?? {})).filter((field: any) => ['CONFIRMED_BY_CODE', 'CONFIRMED_BY_DATA', 'CONFIRMED_BY_SCHEMA'].includes(field.confidence)).length, probable: seed.entities.flatMap((entity: any) => Object.values(entity.fields ?? {})).filter((field: any) => field.confidence === 'PROBABLE').length, unknown: seed.entities.flatMap((entity: any) => Object.values(entity.fields ?? {})).filter((field: any) => field.confidence === 'UNKNOWN').length }; const after = { entities: semantic.entities.length, queryable: semantic.entities.filter((entity: any) => entity.queryable).length, confirmed: fields.filter((field: any) => ['CONFIRMED_BY_CODE', 'CONFIRMED_BY_DATA', 'CONFIRMED_BY_SCHEMA'].includes(field.confidence)).length, probable: fields.filter((field: any) => field.confidence === 'PROBABLE').length, unknown: fields.filter((field: any) => field.confidence === 'UNKNOWN').length };
await mkdir(root, { recursive: true }); await writeFile(join(root, 'semantic.json'), JSON.stringify(semantic, null, 2)); await writeFile(join(root, 'coverage.json'), JSON.stringify({ ...coverage, before, after, profiled: profile.summary ?? null, queryableEntities: semantic.entities.filter((entity: any) => entity.queryable).map((entity: any) => entity.entity) }, null, 2)); await writeFile(join(root, 'unknown-report.json'), JSON.stringify({ generatedAt: semantic.generatedAt, total: unknown.length, objects: unknown }, null, 2)); await writeFile(join(root, 'domain-report.json'), JSON.stringify({ generatedAt: semantic.generatedAt, domains: domainReport }, null, 2)); await writeFile(join(root, 'purchase-request-report.json'), JSON.stringify({ ...prReport, promotion: prSeed?.promotion ?? null }, null, 2)); await writeFile(join(root, 'profile-report.json'), JSON.stringify({ generatedAt: semantic.generatedAt, status: profile.summary ? 'INGESTED' : 'MISSING', summary: profile.summary ?? null }, null, 2)); console.log(JSON.stringify({ coverage, before, after, purchaseRequest: prReport.status, reports: ['unknown-report.json', 'domain-report.json', 'purchase-request-report.json', 'profile-report.json'], preservedSeedEntities: seed.entities.map((entity) => entity.entity) }, null, 2));
