import { readdir, readFile, writeFile, mkdir } from 'node:fs/promises';
import { join, relative } from 'node:path';
import { getSqlServerPool, closeSqlServer } from '../src/config/sqlserver.js';

const root = join(process.cwd(), '..'); const outputRoot = join(root, 'semantic', 'catalog'); const terms = /PRDetail|PURC_PURCHREQUEST_HED|\bPR\.PRNo\b|PRQty|PRDate|Material Description|MaterialID|Status_PR|TglStatus|SecID|PIC/i; const allowed = new Set(['.ts', '.js', '.php', '.sql', '.md']);
async function walk(directory: string): Promise<string[]> { const entries = await readdir(directory, { withFileTypes: true }); const result: string[] = []; for (const entry of entries) { if (entry.name === 'node_modules' || entry.name === 'dist' || entry.name === 'dist-dev' || entry.name === 'dist-scripts' || entry.name === '.git') continue; const path = join(directory, entry.name); if (entry.isDirectory()) result.push(...await walk(path)); else if (allowed.has(entry.name.includes('.') ? `.${entry.name.split('.').at(-1)}` : '')) result.push(path); } return result; }
const files: Array<{ file: string; categories: string[] }> = []; for (const file of await walk(root)) { const content = await readFile(file, 'utf8').catch(() => ''); if (!terms.test(content)) continue; const categories = [...new Set([/PRDetail/i.test(content) ? 'PR_DETAIL_REFERENCE' : '', /PURC_PURCHREQUEST_HED/i.test(content) ? 'PURCHREQUEST_HED_REFERENCE' : '', /\bPR\.PRNo\b|PRNo/i.test(content) ? 'PR_NUMBER_REFERENCE' : '', /PRQty/i.test(content) ? 'QUANTITY_REFERENCE' : '', /PRDate/i.test(content) ? 'DATE_REFERENCE' : '', /Material Description|MaterialID|ProductID|MaterialIDP4/i.test(content) ? 'MATERIAL_REFERENCE' : '', /Status_PR|TglStatus|\bStatus\b/i.test(content) ? 'STATUS_REFERENCE' : '', /SecID|PIC|Requestor|Depart/i.test(content) ? 'REQUESTER_DEPARTMENT_REFERENCE' : ''].filter(Boolean))]; files.push({ file: relative(root, file), categories }); }
const pool = await getSqlServerPool(); const definitionEvidence: Array<Record<string, unknown>> = []; try { const result = await pool.request().query<{ schemaName: string; objectName: string; objectType: string; definition: string }>(`SELECT OBJECT_SCHEMA_NAME(m.object_id) AS schemaName,o.name AS objectName,o.type_desc AS objectType,m.definition FROM sys.sql_modules m JOIN sys.objects o ON o.object_id=m.object_id WHERE m.definition LIKE '%PRDetail%' OR m.definition LIKE '%PRNo%' OR m.definition LIKE '%PRQty%' OR m.definition LIKE '%PURC_PURCHREQUEST_HED%'`); for (const row of result.recordset) { const definition = row.definition; definitionEvidence.push({ object: `${row.schemaName}.${row.objectName}`, objectType: row.objectType, categories: [...new Set([/JOIN[\s\S]{0,300}\bPRDetail\b/i.test(definition) ? 'JOIN_PR_DETAIL' : '', /\bPR\.PRNo\b|\bPRNo\b[\s\S]{0,200}\bPRDetail\b/i.test(definition) ? 'PR_NUMBER_JOIN_OR_REFERENCE' : '', /PRQty/i.test(definition) ? 'QUANTITY_REFERENCE' : '', /PRDate/i.test(definition) ? 'DATE_REFERENCE' : '', /Material Description|MaterialID|ProductID|MaterialIDP4/i.test(definition) ? 'MATERIAL_REFERENCE' : '', /Status_PR|TglStatus/i.test(definition) ? 'STATUS_REFERENCE' : ''].filter(Boolean))] }); } } finally { await closeSqlServer(); }
const codeConfirmedJoin = definitionEvidence.some((item) => (item.categories as string[]).includes('JOIN_PR_DETAIL') && (item.categories as string[]).includes('PR_NUMBER_JOIN_OR_REFERENCE'));
const report = { generatedAt: new Date().toISOString(), sourceFiles: files, databaseDefinitions: definitionEvidence, legacySourceAvailable: files.some((item) => item.file.endsWith('.php')), evidenceSummary: { codeConfirmedJoin, prNumber: codeConfirmedJoin ? 'CONFIRMED_BY_CODE' : 'PROBABLE', requestDate: definitionEvidence.some((item) => (item.categories as string[]).includes('DATE_REFERENCE')) ? 'PROBABLE' : 'PROBABLE', quantity: definitionEvidence.some((item) => (item.categories as string[]).includes('QUANTITY_REFERENCE')) ? 'PROBABLE' : 'PROBABLE', materialDescription: files.some((item) => (item.categories as string[]).includes('MATERIAL_REFERENCE')) ? 'PROBABLE' : 'PROBABLE', status: 'UNKNOWN', requester: 'UNKNOWN', department: 'UNKNOWN' }, rawValuesPersisted: false, rawDefinitionsPersisted: false, geminiInvolved: false };
await mkdir(outputRoot, { recursive: true }); await writeFile(join(outputRoot, 'pr-evidence.json'), JSON.stringify(report, null, 2)); console.log(JSON.stringify({ filesMatched: files.length, definitionsMatched: definitionEvidence.length, codeConfirmedJoin, rawValuesPersisted: false }, null, 2));
