import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { closeSqlServer, getSqlServerPool } from '../src/config/sqlserver.js';

const root = join(process.cwd(), '..', 'semantic', 'catalog'); const pool = await getSqlServerPool();
function context(definition: string, term: string) { const lower = definition.toLowerCase(); const needle = term.toLowerCase(); const out: string[] = []; let pos = 0; while (out.length < 12) { const index = lower.indexOf(needle, pos); if (index < 0) break; out.push(definition.slice(Math.max(0, index - 300), index + needle.length + 700).replace(/\s+/g, ' ').trim().slice(0, 1000)); pos = index + needle.length; } return out; }
function ops(definition: string) { return { insert: /\bINSERT\b/i.test(definition), update: /\bUPDATE\b/i.test(definition), merge: /\bMERGE\b/i.test(definition), select: /\bSELECT\b/i.test(definition), join: /\bJOIN\b/i.test(definition) }; }
try {
  const rows = (await pool.request().query<{ schemaName: string; objectName: string; typeDescription: string; definition: string }>(`SELECT OBJECT_SCHEMA_NAME(m.object_id) AS schemaName,o.name AS objectName,o.type_desc AS typeDescription,m.definition FROM sys.sql_modules m JOIN sys.objects o ON o.object_id=m.object_id WHERE m.definition LIKE '%PURC_PURCHASE_REQUEST%' OR m.definition LIKE '%PURC_PURCHREQUEST_TEMP%' OR m.definition LIKE '%PURCH_MRP%' OR m.definition LIKE '%PRItemNo%' OR m.definition LIKE '%MRPNo%'`)).recordset;
  const targets = ['PURC_PURCHASE_REQUEST', 'PURC_PURCHREQUEST_TEMP', 'PURCH_MRP']; const lineage = rows.map((row) => ({ object: `${row.schemaName}.${row.objectName}`, type: row.typeDescription, operations: ops(row.definition), targetReferences: targets.filter((target) => row.definition.toLowerCase().includes(target.toLowerCase())), fields: ['PRNo', 'PRItemNo', 'ItemNo', 'MaterialId', 'Qty', 'UoM', 'MRPNo', 'DepartId', 'NO_MR', 'KD_BARANG'].filter((field) => row.definition.toLowerCase().includes(field.toLowerCase())), contexts: { insert: context(row.definition, 'INSERT'), prItemNo: context(row.definition, 'PRItemNo'), mrpNo: context(row.definition, 'MRPNo'), qty: context(row.definition, 'Qty'), temp: context(row.definition, 'PURC_PURCHREQUEST_TEMP') } }));
  const finalKeys = (await pool.request().query(`SELECT COUNT_BIG(*) AS rows,COUNT(DISTINCT CONCAT(ISNULL(PRNo,''),'|',ISNULL(CONVERT(varchar(100),PRItemNo),''))) AS pr_item,COUNT(DISTINCT CONCAT(ISNULL(PRNo,''),'|',ISNULL(CONVERT(varchar(100),MaterialId),''))) AS pr_material,COUNT(DISTINCT CONCAT(ISNULL(PRNo,''),'|',ISNULL(CONVERT(varchar(100),PRItemNo),''),'|',ISNULL(CONVERT(varchar(100),MaterialId),''))) AS pr_item_material,SUM(CASE WHEN PRNo IS NULL OR PRItemNo IS NULL THEN 1 ELSE 0 END) AS null_key FROM dbo.PURC_PURCHASE_REQUEST`)).recordset[0];
  const tempKeys = (await pool.request().query(`SELECT COUNT_BIG(*) AS rows,COUNT(DISTINCT CONCAT(ISNULL(PRNo,''),'|',ISNULL(CONVERT(varchar(100),ItemNo),''))) AS pr_item,COUNT(DISTINCT CONCAT(ISNULL(PRNo,''),'|',ISNULL(CONVERT(varchar(100),MaterialId),''))) AS pr_material,COUNT(DISTINCT CONCAT(ISNULL(PRNo,''),'|',ISNULL(CONVERT(varchar(100),ItemNo),''),'|',ISNULL(CONVERT(varchar(100),MaterialId),''))) AS pr_item_material,SUM(CASE WHEN PRNo IS NULL OR ItemNo IS NULL THEN 1 ELSE 0 END) AS null_key FROM dbo.PURC_PURCHREQUEST_TEMP`)).recordset[0];
  const mrpKeys = (await pool.request().query(`SELECT COUNT_BIG(*) AS rows,COUNT(DISTINCT CONCAT(ISNULL(MRPNo,''),'|',ISNULL(CONVERT(varchar(100),MaterialId),''),'|',ISNULL(DepartId,''))) AS mrp_material_depart,COUNT(DISTINCT CONCAT(ISNULL(MRPNo,''),'|',ISNULL(CONVERT(varchar(100),MaterialId),''),'|',ISNULL(DepartId,''),'|',ISNULL(Tipe,''))) AS mrp_material_depart_tipe FROM dbo.PURCH_MRP`)).recordset[0];
  const report = { generatedAt: new Date().toISOString(), lineage, keys: { final: finalKeys, temp: tempKeys, mrp: mrpKeys }, decisions: { finalLineKey: 'PRNo + PRItemNo + MaterialId candidate; write lineage required', tempLineKey: 'PRNo + ItemNo + MaterialId candidate; equivalence to final line not proven', tempFinalMapping: 'UNKNOWN', prCreatedQuantityQueryable: false, runtimeJoinAllowed: false, remainingQuantitySafe: false }, security: { rawRowsPersisted: false, databaseMutation: false, geminiInvolved: false } };
  await mkdir(root, { recursive: true }); await writeFile(join(root, 'write-lineage-coverage-evidence.json'), `${JSON.stringify(report, null, 2)}\n`); console.log(JSON.stringify({ lineageCount: report.lineage.length, keys: report.keys, decisions: report.decisions }, null, 2));
} finally { await closeSqlServer(); }
