import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { closeSqlServer, getSqlServerPool } from '../src/config/sqlserver.js';

type Definition = { schemaName: string; objectName: string; typeDescription: string; definition: string };
const root = join(process.cwd(), '..', 'semantic', 'catalog');
function snippets(definition: string, pattern: string) { const regex = new RegExp(`.{0,220}${pattern}.{0,360}`, 'gi'); return [...definition.matchAll(regex)].map((match) => match[0].replace(/\s+/g, ' ').trim().slice(0, 650)).slice(0, 12); }
function ops(definition: string) { return { select: /\bSELECT\b/i.test(definition), insert: /\bINSERT\b/i.test(definition), update: /\bUPDATE\b/i.test(definition), delete: /\bDELETE\b/i.test(definition), join: /\bJOIN\b/i.test(definition), case: /\bCASE\b/i.test(definition), arithmetic: /(?:Qty\s*[+\-*/]|QtyPR\s*[+\-*/]|QTYBP\s*[+\-*/]|[+\-*/]\s*(?:Qty|QtyPR|QTYBP))/i.test(definition) }; }
const pool = await getSqlServerPool();
try {
  const modules = (await pool.request().query<Definition>(`SELECT OBJECT_SCHEMA_NAME(m.object_id) AS schemaName,o.name AS objectName,o.type_desc AS typeDescription,m.definition FROM sys.sql_modules m JOIN sys.objects o ON o.object_id=m.object_id WHERE m.definition LIKE '%PURCH_MRP%' OR m.definition LIKE '%QTYBP%' OR m.definition LIKE '%QtyPR%' OR m.definition LIKE '%MRPNo%'`)).recordset;
  const code = modules.map((row) => ({ object: `${row.schemaName}.${row.objectName}`, type: row.typeDescription, operations: ops(row.definition), qtyContexts: snippets(row.definition, 'PURCH_MRP.Qty|QTYBP|QtyPR'), insertQtyContexts: snippets(row.definition, 'INSERT[\\s\\S]{0,600}PURCH_MRP'), updateQtyContexts: snippets(row.definition, 'UPDATE[\\s\\S]{0,600}PURCH_MRP'), tipeContexts: snippets(row.definition, 'PURCH_MRP.Tipe|Tipe\\s*='), mrpNoContexts: snippets(row.definition, 'MRPNo') }));
  const quality = (await pool.request().query<Record<string, number>>(`SELECT COUNT_BIG(*) AS row_count,COUNT_BIG(Qty) AS non_null_count,COUNT(DISTINCT Qty) AS distinct_count,MIN(Qty) AS min_qty,MAX(Qty) AS max_qty,SUM(CASE WHEN Qty=0 THEN 1 ELSE 0 END) AS zero_count,SUM(CASE WHEN Qty<0 THEN 1 ELSE 0 END) AS negative_count,SUM(CASE WHEN Qty>0 THEN 1 ELSE 0 END) AS positive_count,COUNT(DISTINCT CONCAT(ISNULL(MRPNo,''),'|',ISNULL(CONVERT(varchar(100),MaterialId),''))) AS distinct_mrp_material,COUNT(DISTINCT CONCAT(ISNULL(MRPNo,''),'|',ISNULL(CONVERT(varchar(100),MaterialId),''),'|',ISNULL(DepartId,''))) AS distinct_mrp_material_depart,COUNT(DISTINCT MaterialId) AS distinct_material,COUNT(DISTINCT MRPNo) AS distinct_mrp_no,COUNT(DISTINCT Tipe) AS distinct_tipe FROM dbo.PURCH_MRP`)).recordset[0];
  const byType = (await pool.request().query(`SELECT Tipe AS tipe,COUNT_BIG(*) AS row_count,COUNT(DISTINCT MRPNo) AS distinct_mrp_no,COUNT(DISTINCT MaterialId) AS distinct_material,SUM(Qty) AS total_qty FROM dbo.PURCH_MRP GROUP BY Tipe`)).recordset.map((row) => ({ tipe: row.tipe === null ? null : 'present', rowCount: Number(row.row_count ?? 0), distinctMrpNo: Number(row.distinct_mrp_no ?? 0), distinctMaterial: Number(row.distinct_material ?? 0), totalQtyPresent: row.total_qty !== null }));
  const qtyPrView = (await pool.request().query(`SELECT COUNT_BIG(*) AS row_count,COUNT(DISTINCT MRPNo) AS distinct_mrp_no,COUNT(DISTINCT MaterialId) AS distinct_material,SUM(CASE WHEN QtyPr IS NULL THEN 1 ELSE 0 END) AS null_qtypr FROM dbo.PURCV_BP_PR`)).recordset[0];
  const report = { generatedAt: new Date().toISOString(), source: 'dbo.PURCH_MRP', security: { rawRowsPersisted: false, databaseMutation: false, geminiInvolved: false }, quality: { rowCount: Number(quality.row_count ?? 0), nullCount: Number(quality.row_count ?? 0) - Number(quality.non_null_count ?? 0), distinctCount: Number(quality.distinct_count ?? 0), min: quality.min_qty, max: quality.max_qty, zeroCount: Number(quality.zero_count ?? 0), negativeCount: Number(quality.negative_count ?? 0), positiveCount: Number(quality.positive_count ?? 0), distinctMrpMaterial: Number(quality.distinct_mrp_material ?? 0), distinctMrpMaterialDepart: Number(quality.distinct_mrp_material_depart ?? 0), distinctMaterial: Number(quality.distinct_material ?? 0), distinctMrpNo: Number(quality.distinct_mrp_no ?? 0), distinctTipe: Number(quality.distinct_tipe ?? 0) }, byType, qtyPrView: { rowCount: Number(qtyPrView.row_count ?? 0), distinctMrpNo: Number(qtyPrView.distinct_mrp_no ?? 0), distinctMaterial: Number(qtyPrView.distinct_material ?? 0), nullQtyPr: Number(qtyPrView.null_qtypr ?? 0) }, codeEvidence: code, semanticDecision: { meaning: 'UNRESOLVED', confidence: 'UNKNOWN', semanticField: null, queryable: false, missingEvidence: ['Explicit code lineage proving whether PURCH_MRP.Qty is requirement/planned/demand quantity', 'Validated row grain and duplicate policy before enabling SUM', 'Clear business distinction from QtyPR/PR quantity'] } };
  await mkdir(root, { recursive: true }); await writeFile(join(root, 'purch-mrp-qty-evidence.json'), `${JSON.stringify(report, null, 2)}\n`); console.log(JSON.stringify({ source: report.source, quality: report.quality, qtyPrView: report.qtyPrView, semanticDecision: report.semanticDecision }, null, 2));
} finally { await closeSqlServer(); }
