import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { closeSqlServer, getSqlServerPool } from '../src/config/sqlserver.js';

const root = join(process.cwd(), '..', 'semantic', 'catalog');
const pool = await getSqlServerPool();
const safe = (value: unknown) => typeof value === 'number' ? value : Number(value ?? 0);
try {
  const view = (await pool.request().query(`SELECT COUNT_BIG(*) AS view_rows,COUNT(DISTINCT CONCAT(ISNULL(MRPNo,''),'|',ISNULL(CONVERT(varchar(100),MaterialId),''))) AS distinct_mrp_material,COUNT(DISTINCT CONCAT(ISNULL(MRPNo,''),'|',ISNULL(CONVERT(varchar(100),MaterialId),''),'|',ISNULL(PRNo,''))) AS distinct_mrp_material_pr,COUNT(DISTINCT CONCAT(ISNULL(MRPNo,''),'|',ISNULL(CONVERT(varchar(100),MaterialId),''),'|',ISNULL(PRNo,''),'|',ISNULL(CONVERT(varchar(100),QtyPr),''))) AS distinct_with_qtypr,SUM(CASE WHEN QtyPr IS NULL AND PRNo IS NULL THEN 1 ELSE 0 END) AS null_both,SUM(CASE WHEN QtyPr IS NULL AND PRNo IS NOT NULL THEN 1 ELSE 0 END) AS null_qtypr_pr_present,SUM(CASE WHEN QtyPr IS NOT NULL AND PRNo IS NULL THEN 1 ELSE 0 END) AS qtypr_present_pr_null,SUM(CASE WHEN QtyPr IS NOT NULL AND PRNo IS NOT NULL THEN 1 ELSE 0 END) AS both_present FROM dbo.PURCV_BP_PR`)).recordset[0] as Record<string, unknown>;
  const fanout = (await pool.request().query(`WITH grouped AS (SELECT MRPNo,MaterialId,COUNT_BIG(*) AS matches FROM dbo.PURCV_BP_PR GROUP BY MRPNo,MaterialId) SELECT COUNT_BIG(*) AS groups,MIN(matches) AS min_matches,MAX(matches) AS max_matches,AVG(CONVERT(float,matches)) AS average_matches,SUM(CASE WHEN matches=1 THEN 1 ELSE 0 END) AS one_match,SUM(CASE WHEN matches>1 THEN 1 ELSE 0 END) AS multiple_matches FROM grouped`)).recordset[0] as Record<string, unknown>;
  const prFanout = (await pool.request().query(`WITH grouped AS (SELECT PRNo,MRPNo,MaterialId,COUNT_BIG(*) AS matches FROM dbo.PURCV_BP_PR WHERE PRNo IS NOT NULL GROUP BY PRNo,MRPNo,MaterialId) SELECT COUNT_BIG(*) AS groups,MAX(matches) AS max_matches,SUM(CASE WHEN matches>1 THEN 1 ELSE 0 END) AS duplicate_groups FROM grouped`)).recordset[0] as Record<string, unknown>;
  const grain = (await pool.request().query(`SELECT COUNT_BIG(*) AS rows,COUNT(DISTINCT CONCAT(ISNULL(MRPNo,''),'|',ISNULL(CONVERT(varchar(100),MaterialId),''))) AS distinct_mrp_material,COUNT(DISTINCT CONCAT(ISNULL(MRPNo,''),'|',ISNULL(CONVERT(varchar(100),MaterialId),''),'|',ISNULL(DepartId,''))) AS distinct_mrp_material_depart,COUNT(DISTINCT CONCAT(ISNULL(MRPNo,''),'|',ISNULL(CONVERT(varchar(100),MaterialId),''),'|',ISNULL(DepartId,''),'|',ISNULL(Tipe,''))) AS distinct_mrp_material_depart_tipe FROM dbo.PURCH_MRP`)).recordset[0] as Record<string, unknown>;
  const report = { generatedAt: new Date().toISOString(), source: 'dbo.PURCV_BP_PR', viewAggregate: Object.fromEntries(Object.entries(view).map(([key, value]) => [key, safe(value)])), mrpPrFanout: Object.fromEntries(Object.entries(fanout).map(([key, value]) => [key, safe(value)])), prLineFanout: Object.fromEntries(Object.entries(prFanout).map(([key, value]) => [key, safe(value)])), mrpGrain: Object.fromEntries(Object.entries(grain).map(([key, value]) => [key, safe(value)])), decisions: { prCreatedQuantity: { rowLevelSafe: false, aggregatePerMrpLineSafe: false, queryable: false, runtimeJoinAllowed: false }, nullAsZeroSafe: false, remainingQuantitySafe: false, reason: 'View groups PR-side rows at a finer grain than the outer MRPNo+MaterialId join and exhibits fanout/null ambiguity.' }, security: { rawRowsPersisted: false, databaseMutation: false, geminiInvolved: false } };
  await mkdir(root, { recursive: true }); await writeFile(join(root, 'mrp-pr-grain-evidence.json'), `${JSON.stringify(report, null, 2)}\n`); console.log(JSON.stringify(report, null, 2));
} finally { await closeSqlServer(); }
