import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { closeSqlServer, getSqlServerPool } from '../src/config/sqlserver.js';

const root = join(process.cwd(), '..', 'semantic', 'catalog'); const pool = await getSqlServerPool();
function snippet(definition: string, term: string) { const lower = definition.toLowerCase(); const needle = term.toLowerCase(); const output: string[] = []; let start = 0; while (output.length < 10) { const index = lower.indexOf(needle, start); if (index < 0) break; output.push(definition.slice(Math.max(0, index - 260), index + term.length + 600).replace(/\s+/g, ' ').trim().slice(0, 900)); start = index + term.length; } return output; }
try {
  const definition = (await pool.request().query<{ definition: string }>(`SELECT m.definition FROM sys.sql_modules m JOIN sys.objects o ON o.object_id=m.object_id WHERE OBJECT_SCHEMA_NAME(o.object_id)='dbo' AND o.name='PURCV_BP_PR'`)).recordset[0]?.definition ?? '';
  const lineage = { qtyPr: snippet(definition, 'QtyPr'), prNo: snippet(definition, 'PRNo'), noMr: snippet(definition, 'NO_MR'), materialId: snippet(definition, 'KD_BARANG|MaterialId'), aliases: snippet(definition, 'FROM \(SELECT bb\.MRPNo') };
  const view = (await pool.request().query(`SELECT COUNT_BIG(*) AS view_rows,COUNT(DISTINCT CONCAT(ISNULL(MRPNo,''),'|',ISNULL(CONVERT(varchar(100),MaterialId),''))) AS distinct_mrp_material,COUNT(DISTINCT CONCAT(ISNULL(MRPNo,''),'|',ISNULL(CONVERT(varchar(100),MaterialId),''),'|',ISNULL(PRNo,''))) AS distinct_mrp_material_pr,COUNT(DISTINCT CONCAT(ISNULL(MRPNo,''),'|',ISNULL(CONVERT(varchar(100),MaterialId),''),'|',ISNULL(PRNo,''),'|',ISNULL(CONVERT(varchar(100),QtyPr),''))) AS distinct_with_qtypr,SUM(CASE WHEN QtyPr IS NULL AND PRNo IS NULL THEN 1 ELSE 0 END) AS null_both,SUM(CASE WHEN QtyPr IS NULL AND PRNo IS NOT NULL THEN 1 ELSE 0 END) AS null_qtypr_pr_present,SUM(CASE WHEN QtyPr IS NOT NULL AND PRNo IS NULL THEN 1 ELSE 0 END) AS qtypr_present_pr_null,SUM(CASE WHEN QtyPr IS NOT NULL AND PRNo IS NOT NULL THEN 1 ELSE 0 END) AS both_present FROM dbo.PURCV_BP_PR`)).recordset[0] as Record<string, number>;
  const mrpFanout = (await pool.request().query(`WITH g AS (SELECT MRPNo,MaterialId,COUNT_BIG(*) AS n FROM dbo.PURCV_BP_PR GROUP BY MRPNo,MaterialId) SELECT COUNT_BIG(*) AS groups,MIN(n) AS min_n,MAX(n) AS max_n,AVG(CONVERT(float,n)) AS avg_n,SUM(CASE WHEN n=1 THEN 1 ELSE 0 END) AS one,SUM(CASE WHEN n>1 THEN 1 ELSE 0 END) AS many FROM g`)).recordset[0] as Record<string, number>;
  const prFanout = (await pool.request().query(`WITH g AS (SELECT PRNo,MRPNo,MaterialId,COUNT_BIG(*) AS n FROM dbo.PURCV_BP_PR WHERE PRNo IS NOT NULL GROUP BY PRNo,MRPNo,MaterialId) SELECT COUNT_BIG(*) AS groups,MAX(n) AS max_n,SUM(CASE WHEN n>1 THEN 1 ELSE 0 END) AS duplicate_groups FROM g`)).recordset[0] as Record<string, number>;
  const mrpGrain = (await pool.request().query(`SELECT COUNT_BIG(*) AS rows,COUNT(DISTINCT CONCAT(ISNULL(MRPNo,''),'|',ISNULL(CONVERT(varchar(100),MaterialId),''))) AS mrp_material,COUNT(DISTINCT CONCAT(ISNULL(MRPNo,''),'|',ISNULL(CONVERT(varchar(100),MaterialId),''),'|',ISNULL(DepartId,''))) AS mrp_material_depart,COUNT(DISTINCT CONCAT(ISNULL(MRPNo,''),'|',ISNULL(CONVERT(varchar(100),MaterialId),''),'|',ISNULL(DepartId,''),'|',ISNULL(Tipe,''))) AS mrp_material_depart_tipe FROM dbo.PURCH_MRP`)).recordset[0] as Record<string, number>;
  const units = (await pool.request().query(`SELECT TABLE_SCHEMA AS schema_name,TABLE_NAME AS table_name,COLUMN_NAME AS column_name FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME IN ('PURCH_MRP','PURCV_BP_PR','PURC_PURCHASE_REQUEST','PURC_PURCHREQUEST_TEMP') AND (COLUMN_NAME LIKE '%UoM%' OR COLUMN_NAME LIKE '%Unit%' OR COLUMN_NAME LIKE '%Satuan%')`)).recordset.map((row) => ({ schema: row.schema_name, object: row.table_name, column: row.column_name }));
  const report = { generatedAt: new Date().toISOString(), source: 'dbo.PURCV_BP_PR', definitionInspected: Boolean(definition), lineage, aggregates: { view: view, mrpFanout, prFanout, mrpGrain }, units, decisions: { prCreatedQuantity: { meaning: 'Quantity planning MRP yang sudah dibuat Purchase Request', confidence: 'CONFIRMED_BY_HUMAN', lineageValidated: true, grainValidated: false, rowLevelSafe: false, aggregatePerMrpLineSafe: false, queryable: false, runtimeJoinAllowed: false }, nullAsZeroSafe: false, plannedQtyDuplicated: true, prQtyDuplicated: true, preAggregationRequired: true, remainingQuantitySafe: false }, security: { rawRowsPersisted: false, databaseMutation: false, geminiInvolved: false } };
  await mkdir(root, { recursive: true }); await writeFile(join(root, 'mrp-pr-deep-evidence.json'), `${JSON.stringify(report, null, 2)}\n`); console.log(JSON.stringify({ definitionInspected: report.definitionInspected, aggregates: report.aggregates, units: report.units, decisions: report.decisions }, null, 2));
} finally { await closeSqlServer(); }
