import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { getSqlServerPool, closeSqlServer } from '../src/config/sqlserver.js';

type Column = { columnName: string; datatype: string; nullable?: string; maxLength?: number | null; precision?: number | null; scale?: number | null };
type Obj = { schemaName: string; objectName: string; objectType: string; columns?: Column[]; keys?: Array<{ columnName: string; constraintType: string }>; indexes?: Array<{ indexName: string; isUnique?: boolean; indexType?: string }> };
type Catalog = { objects: Obj[]; dependencies: Array<Record<string, string>>; storedProcedures: Array<Record<string, string>> };
const root = join(process.cwd(), '..', 'semantic', 'catalog');
const qualified = (name: string) => `[${name.replace(/]/g, ']]')}]`;
const sourceNames = ['PURC_PURCHREQUEST_TEMP', 'PURC_PURCHASE_REQUEST'] as const;
const confidence = (evidence: string[]) => evidence.length >= 3 ? 'PROBABLE' : 'UNKNOWN';
const catalog = JSON.parse(await readFile(join(root, 'schema.json'), 'utf8')) as Catalog;
const objects = sourceNames.map((name) => catalog.objects.find((object) => object.schemaName === 'dbo' && object.objectName === name)).filter((object): object is Obj => Boolean(object));
const byName = (name: string) => objects.find((object) => object.objectName === name);
const objectMetadata = (object: Obj) => ({ object: `dbo.${object.objectName}`, objectType: object.objectType, columns: object.columns ?? [], primaryKey: (object.keys ?? []).filter((key) => key.constraintType === 'PRIMARY KEY').map((key) => key.columnName), foreignKeys: (object.keys ?? []).filter((key) => key.constraintType === 'FOREIGN KEY'), indexes: object.indexes ?? [], schemaMetadataAvailable: true });
const fieldCandidates = (object: Obj | undefined) => {
  const names = new Set((object?.columns ?? []).map((column) => column.columnName.toLowerCase()));
  const choose = (patterns: RegExp[]) => (object?.columns ?? []).filter((column) => patterns.some((pattern) => pattern.test(column.columnName))).map((column) => column.columnName);
  return { pr_number: choose([/^prno$/i, /^req_no$/i]), request_date: choose([/prdate|request.?date|inp_date/i]), material_code: choose([/^materialid$/i, /material.?code|item.?code/i]), material_description: choose([/materialname|description|specification|purpose/i]), quantity: choose([/^qty$|quantity/i]), status: choose([/^status$|status_info/i]), requester: choose([/requestor|requester|inp_by/i]), department: choose([/^dept$|depart/i]), approval_status: choose([/^approval$|approval_info|approval_proc/i]), approval_date: choose([/approval.?date|appdate/i]) , _knownColumns: [...names] };
};
async function aggregate(pool: Awaited<ReturnType<typeof getSqlServerPool>>, object: string, columns: string[]) {
  const dateCandidates = columns.filter((column) => /date|time|created|updated|inp_|upd_/i.test(column));
  const selects = [`COUNT_BIG(*) AS rowCount`];
  for (const column of columns.filter((column) => /prno|req_no|materialid|qty|status|requestor|dept|approval/i.test(column))) selects.push(`COUNT(${qualified(column)}) AS ${qualified(`nonNull_${column}`)}`);
  for (const column of dateCandidates.slice(0, 8)) { selects.push(`MIN(TRY_CONVERT(datetime2, ${qualified(column)})) AS ${qualified(`min_${column}`)}`); selects.push(`MAX(TRY_CONVERT(datetime2, ${qualified(column)})) AS ${qualified(`max_${column}`)}`); }
  try { const result = await pool.request().query(`SELECT ${selects.join(', ')} FROM [dbo].${qualified(object)}`); return { status: 'AVAILABLE', aggregates: result.recordset[0] ?? {} }; } catch (error) { return { status: 'UNAVAILABLE', reason: error instanceof Error ? error.name : 'QUERY_ERROR' }; }
}
async function match(pool: Awaited<ReturnType<typeof getSqlServerPool>>, left: string, right: string, column: string) {
  const query = `WITH l AS (SELECT TOP (@limit) NULLIF(LTRIM(RTRIM(CONVERT(nvarchar(255), ${qualified(column)}))), '') AS value FROM [dbo].${qualified(left)} WHERE ${qualified(column)} IS NOT NULL), r AS (SELECT DISTINCT NULLIF(LTRIM(RTRIM(CONVERT(nvarchar(255), ${qualified(column)}))), '') AS value FROM [dbo].${qualified(right)} WHERE ${qualified(column)} IS NOT NULL) SELECT COUNT_BIG(*) AS sampleSize, SUM(CASE WHEN r.value IS NULL THEN 0 ELSE 1 END) AS matched FROM l LEFT JOIN r ON r.value=l.value WHERE l.value IS NOT NULL`;
  try { const row = (await pool.request().input('limit', Number(process.env.SEMANTIC_VALIDATION_SAMPLE_SIZE ?? 10000)).query(query)).recordset[0] as Record<string, number>; const sampleSize = Number(row.sampleSize ?? 0); const matched = Number(row.matched ?? 0); return { status: 'AVAILABLE', sampleSize, matched, unmatched: sampleSize - matched, matchRate: sampleSize ? matched / sampleSize : 0 }; } catch (error) { return { status: 'UNAVAILABLE', reason: error instanceof Error ? error.name : 'QUERY_ERROR' }; }
}
async function lifecycleMatch(pool: Awaited<ReturnType<typeof getSqlServerPool>>) {
  const query = `WITH t AS (SELECT DISTINCT NULLIF(LTRIM(RTRIM(CONVERT(nvarchar(255),[PRNo]))),'') AS value FROM [dbo].[PURC_PURCHREQUEST_TEMP] WHERE [PRNo] IS NOT NULL), f AS (SELECT DISTINCT NULLIF(LTRIM(RTRIM(CONVERT(nvarchar(255),[PRNo]))),'') AS value FROM [dbo].[PURC_PURCHASE_REQUEST] WHERE [PRNo] IS NOT NULL) SELECT (SELECT COUNT_BIG(*) FROM t) AS tempDistinctPrNumbers,(SELECT COUNT_BIG(*) FROM f) AS finalDistinctPrNumbers,(SELECT COUNT_BIG(*) FROM t JOIN f ON t.value=f.value) AS matched,(SELECT COUNT_BIG(*) FROM t LEFT JOIN f ON t.value=f.value WHERE f.value IS NULL) AS tempOnly,(SELECT COUNT_BIG(*) FROM f LEFT JOIN t ON f.value=t.value WHERE t.value IS NULL) AS finalOnly`;
  try { const row = (await pool.request().query(query)).recordset[0] as Record<string, number>; const tempDistinctPrNumbers = Number(row.tempDistinctPrNumbers ?? 0); const finalDistinctPrNumbers = Number(row.finalDistinctPrNumbers ?? 0); const matched = Number(row.matched ?? 0); return { status: 'AVAILABLE', tempDistinctPrNumbers, finalDistinctPrNumbers, matched, tempOnly: Number(row.tempOnly ?? 0), finalOnly: Number(row.finalOnly ?? 0), matchRate: tempDistinctPrNumbers ? matched / tempDistinctPrNumbers : 0 }; } catch (error) { return { status: 'UNAVAILABLE', reason: error instanceof Error ? error.name : 'QUERY_ERROR' }; }
}
async function materialTargetMatch(pool: Awaited<ReturnType<typeof getSqlServerPool>>, target: { object: string; column: string; datatype: string }) {
  const source = '[dbo].[PURC_PURCHASE_REQUEST]'; const targetObject = target.object.split('.').map(qualified).join('.'); const sourceType = /^(char|nchar|varchar|nvarchar)$/i.test('char'); const equality = sourceType ? `LTRIM(RTRIM(CONVERT(nvarchar(255),s.value)))=LTRIM(RTRIM(CONVERT(nvarchar(255),t.${qualified(target.column)})))` : `TRY_CONVERT(nvarchar(255),s.value)=TRY_CONVERT(nvarchar(255),t.${qualified(target.column)})`;
  const query = `WITH sample AS (SELECT TOP (@limit) [MaterialId] AS value FROM ${source} WHERE [MaterialId] IS NOT NULL), marked AS (SELECT CASE WHEN t.${qualified(target.column)} IS NULL THEN 0 ELSE 1 END AS matched FROM sample s LEFT JOIN ${targetObject} t ON ${equality}) SELECT COUNT_BIG(*) AS sampleSize,SUM(matched) AS matched,SUM(CASE WHEN matched=0 THEN 1 ELSE 0 END) AS unmatched FROM marked`;
  try { const row = (await pool.request().input('limit', Number(process.env.SEMANTIC_VALIDATION_SAMPLE_SIZE ?? 10000)).query(query)).recordset[0] as Record<string, number>; const sampleSize = Number(row.sampleSize ?? 0); const matched = Number(row.matched ?? 0); const matchRate = sampleSize ? matched / sampleSize : 0; return { source: 'dbo.PURC_PURCHASE_REQUEST.MaterialId', target: `dbo.${target.object}.${target.column}`, sampleSize, matched, unmatched: Number(row.unmatched ?? 0), matchRate, confidence: matchRate >= 0.99 ? 'CONFIRMED_BY_DATA' : matchRate >= 0.9 ? 'PROBABLE' : 'UNKNOWN' }; } catch (error) { return { source: 'dbo.PURC_PURCHASE_REQUEST.MaterialId', target: `dbo.${target.object}.${target.column}`, status: 'VALIDATION_ERROR', reason: error instanceof Error ? error.name : 'QUERY_ERROR' }; }
}
let pool: Awaited<ReturnType<typeof getSqlServerPool>> | undefined;
try { try { pool = await getSqlServerPool(); } catch { pool = undefined; }
  const metadata = Object.fromEntries(objects.map((object) => [object.objectName, objectMetadata(object)]));
  const candidates = Object.fromEntries(objects.map((object) => [object.objectName, fieldCandidates(object)]));
  const commonFields = [...new Set(objects.flatMap((object) => (object.columns ?? []).map((column) => column.columnName)))].filter((column) => objects.every((object) => (object.columns ?? []).some((item) => item.columnName.toLowerCase() === column.toLowerCase())));
  const uniqueFields = Object.fromEntries(objects.map((object) => [object.objectName, (object.columns ?? []).map((column) => column.columnName).filter((column) => !commonFields.some((common) => common.toLowerCase() === column.toLowerCase()))]));
  const deps = catalog.dependencies.filter((item) => sourceNames.includes(String(item.toObject) as typeof sourceNames[number]) || sourceNames.includes(String(item.fromObject) as typeof sourceNames[number]));
  const procedures = catalog.storedProcedures.filter((item) => /PURC_PURCHREQUEST_TEMP|PURC_PURCHASE_REQUEST/i.test(JSON.stringify(item)));
  const populations = pool ? Object.fromEntries(await Promise.all(objects.map(async (object) => [object.objectName, await aggregate(pool!, object.objectName, (object.columns ?? []).map((column) => column.columnName))]))) : { status: 'UNAVAILABLE', reason: 'SQL_SERVER_NOT_CONFIGURED' };
  const lifecycle = pool ? { prNo: await lifecycleMatch(pool), sampledColumnMatch: await match(pool, 'PURC_PURCHREQUEST_TEMP', 'PURC_PURCHASE_REQUEST', 'PRNo'), reqNoToPrNo: { status: 'NOT_RUN', reason: 'different candidate identifiers; no schema/dependency evidence makes Req_No a validated cross-table key' } } : { status: 'UNAVAILABLE', reason: 'SQL_SERVER_NOT_CONFIGURED' };
  const final = byName('PURC_PURCHASE_REQUEST'); const temp = byName('PURC_PURCHREQUEST_TEMP');
  const materialTargets = catalog.objects.filter((object) => object.objectType === 'TABLE' && /(material|matcatalog|item|product)/i.test(object.objectName)).flatMap((object) => (object.columns ?? []).filter((column) => /material.?id|material.?code|item.?id|product.?id/i.test(column.columnName)).map((column) => ({ target: `dbo.${object.objectName}.${column.columnName}`, datatype: column.datatype })));
  const materialChecks = pool ? await Promise.all(materialTargets.filter((target) => /^(char|nchar|varchar|nvarchar|int|bigint|smallint|tinyint|numeric|decimal)$/i.test(target.datatype)).map((target) => materialTargetMatch(pool!, { object: target.target.split('.')[1], column: target.target.split('.').at(-1)!, datatype: target.datatype }))) : [];
  const report = { generatedAt: new Date().toISOString(), persisted: 'schema-metadata-and-bounded-aggregates-only', security: { rawValuesPersisted: false, rawRowsPersisted: false, geminiInvolved: false, databaseMutation: false }, directInspection: { temp: { activeWorkflowRowsObserved: true, searchableDescriptionColumn: 'MaterialName', searchableDescriptionEvidence: 'direct database inspection' }, final: { recentSpecificationNullObserved: true, recentBrandNullObserved: true, primaryTextSearchPath: 'NOT_SPECIFICATION_OR_BRAND' } }, sources: metadata, populations, dateRanges: populations, dependencies: deps, viewAndProcedureReferences: procedures, comparison: { commonFields, uniqueFields, lifecycle }, roleAssessment: { temp: { role: 'TEMP_OR_WORKFLOW_SOURCE', confidence: confidence(['approval fields', 'requester/department fields', 'workflow dates']), humanApprovalRequired: true, evidence: ['approval workflow fields', 'requester and department fields', 'CDate/AppDate/Purpose_Date fields', 'direct active workflow observation'] }, final: { role: 'FINAL_OR_ACTIVE_LINE_SOURCE_CANDIDATE', confidence: confidence(['line-item key fields', 'PRNo/PRItemNo', 'input/update dates']), humanApprovalRequired: true, evidence: ['PRNo and PRItemNo line identity', 'MaterialId and Qty', 'inp_date and upd_date', 'Specification and Brand null in inspected recent rows'] }, authoritative: { status: 'NOT_CONFIRMED', source: null, reason: 'Source role and field mappings still require explicit human approval.' } }, candidateSemanticFields: { [sourceNames[0]]: candidates[sourceNames[0]], [sourceNames[1]]: candidates[sourceNames[1]] }, materialValidation: { source: 'dbo.PURC_PURCHASE_REQUEST.MaterialId', candidateTargets: materialTargets, checks: materialChecks, status: pool ? 'COMPLETED_BOUNDED' : 'NOT_RUN', reason: pool ? 'Aggregate validation only; raw values are not persisted.' : 'SQL_SERVER_NOT_CONFIGURED' }, targetQuery: { question: 'No PR laptop ASUS yang qty 5 apa?', queryable: false, physicalPath: null, fields: ['pr_number', 'material_description', 'quantity'], confidence: 'UNKNOWN', reason: 'TEMP source role and four TEMP field approvals are not confirmed.' }, legacySources: [{ source: 'dbo.PR', status: 'LEGACY_OR_ALTERNATE', reason: 'Prior human approvals confirm meaning only; source authority is under re-investigation.' }, { source: 'dbo.PRDetail', status: 'LEGACY_OR_ALTERNATE', reason: 'Prior human approvals confirm meaning only; source authority is under re-investigation.' }] };
  await mkdir(root, { recursive: true }); await writeFile(join(root, 'pr-source-investigation.json'), JSON.stringify(report, null, 2)); console.log(JSON.stringify({ authoritative: report.roleAssessment.authoritative, targetQuery: report.targetQuery, rawRowsPersisted: false }, null, 2));
} finally { if (pool) await closeSqlServer(); }
