import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { closeSqlServer, getSqlServerPool } from '../src/config/sqlserver.js';

const root = join(process.cwd(), '..', 'semantic', 'catalog'); const pool = await getSqlServerPool();
try {
  const finalSchema = (await pool.request().query(`SELECT c.name AS column_name,t.name AS datatype,c.max_length,c.precision,c.scale,c.is_nullable,CASE WHEN pk.column_id IS NULL THEN 0 ELSE 1 END AS is_pk FROM sys.columns c JOIN sys.objects o ON o.object_id=c.object_id JOIN sys.types t ON t.user_type_id=c.user_type_id LEFT JOIN (SELECT ic.object_id,ic.column_id FROM sys.index_columns ic JOIN sys.indexes i ON i.object_id=ic.object_id AND i.index_id=ic.index_id WHERE i.is_primary_key=1) pk ON pk.object_id=c.object_id AND pk.column_id=c.column_id WHERE SCHEMA_NAME(o.schema_id)='dbo' AND o.name='PURC_PURCHASE_REQUEST' ORDER BY c.column_id`)).recordset;
  const finalQuality = (await pool.request().query(`SELECT COUNT_BIG(*) AS rows,COUNT(Qty) AS qty_present,COUNT(DISTINCT CONCAT(ISNULL(PRNo,''),'|',ISNULL(CONVERT(varchar(100),PRItemNo),''))) AS distinct_pr_item,COUNT(DISTINCT CONCAT(ISNULL(PRNo,''),'|',ISNULL(CONVERT(varchar(100),PRItemNo),''),'|',ISNULL(CONVERT(varchar(100),MaterialId),''))) AS distinct_pr_item_material,SUM(CASE WHEN Qty IS NULL THEN 1 ELSE 0 END) AS qty_null FROM dbo.PURC_PURCHASE_REQUEST`)).recordset[0] as Record<string, number>;
  const tempFinal = (await pool.request().query(`WITH g AS (SELECT t.PRNo,t.ItemNo,t.MaterialId,COUNT(f.PRNo) AS n FROM dbo.PURC_PURCHREQUEST_TEMP t LEFT JOIN dbo.PURC_PURCHASE_REQUEST f ON f.PRNo=t.PRNo AND f.MaterialId=t.MaterialId GROUP BY t.PRNo,t.ItemNo,t.MaterialId) SELECT COUNT_BIG(*) AS temp_lines,SUM(CASE WHEN n=0 THEN 1 ELSE 0 END) AS unmatched,SUM(CASE WHEN n=1 THEN 1 ELSE 0 END) AS one_match,SUM(CASE WHEN n>1 THEN 1 ELSE 0 END) AS many_match,MAX(n) AS max_match FROM g`)).recordset[0] as Record<string, number>;
  const tempFinalItem = (await pool.request().query(`WITH g AS (SELECT t.PRNo,t.ItemNo,t.MaterialId,COUNT(f.PRNo) AS n FROM dbo.PURC_PURCHREQUEST_TEMP t LEFT JOIN dbo.PURC_PURCHASE_REQUEST f ON f.PRNo=t.PRNo AND f.PRItemNo=t.ItemNo AND f.MaterialId=t.MaterialId GROUP BY t.PRNo,t.ItemNo,t.MaterialId) SELECT COUNT_BIG(*) AS temp_lines,SUM(CASE WHEN n=0 THEN 1 ELSE 0 END) AS unmatched,SUM(CASE WHEN n=1 THEN 1 ELSE 0 END) AS one_match,SUM(CASE WHEN n>1 THEN 1 ELSE 0 END) AS many_match,MAX(n) AS max_match FROM g`)).recordset[0] as Record<string, number>;
  const mrpTemp = (await pool.request().query(`WITH g AS (SELECT m.MRPNo,m.MaterialId,m.DepartId,COUNT(t.Id) AS n FROM dbo.PURCH_MRP m LEFT JOIN dbo.PURC_PURCHREQUEST_TEMP t ON t.MRPNo=m.MRPNo AND t.MaterialId=m.MaterialId GROUP BY m.MRPNo,m.MaterialId,m.DepartId) SELECT COUNT_BIG(*) AS groups,SUM(CASE WHEN n=0 THEN 1 ELSE 0 END) AS unmatched,SUM(CASE WHEN n=1 THEN 1 ELSE 0 END) AS one_match,SUM(CASE WHEN n>1 THEN 1 ELSE 0 END) AS many_match,MAX(n) AS max_match FROM g`)).recordset[0] as Record<string, number>;
  const duplicateM = (await pool.request().query(`WITH g AS (SELECT MRPNo,MaterialId,DepartId,MRPDate,Status,Tipe,UoM,COUNT_BIG(*) AS n,COUNT(DISTINCT Qty) AS qty_values FROM dbo.PURCH_MRP GROUP BY MRPNo,MaterialId,DepartId,MRPDate,Status,Tipe,UoM) SELECT SUM(CASE WHEN n>1 THEN 1 ELSE 0 END) AS duplicate_groups,SUM(CASE WHEN n>1 THEN n ELSE 0 END) AS rows_in_duplicate_groups,MAX(n) AS max_multiplicity,SUM(CASE WHEN n>1 AND qty_values>1 THEN 1 ELSE 0 END) AS differing_qty_groups FROM g`)).recordset[0] as Record<string, number>;
  const uom = (await pool.request().query(`SELECT COUNT_BIG(*) AS matched_lines,SUM(CASE WHEN UPPER(LTRIM(RTRIM(m.UoM)))=UPPER(LTRIM(RTRIM(f.UoM))) THEN 1 ELSE 0 END) AS same_uom,SUM(CASE WHEN m.UoM IS NULL OR f.UoM IS NULL THEN 1 ELSE 0 END) AS null_uom,SUM(CASE WHEN m.UoM IS NOT NULL AND f.UoM IS NOT NULL AND UPPER(LTRIM(RTRIM(m.UoM)))<>UPPER(LTRIM(RTRIM(f.UoM))) THEN 1 ELSE 0 END) AS different_uom FROM dbo.PURCH_MRP m JOIN dbo.PURC_PURCHREQUEST_TEMP t ON t.MRPNo=m.MRPNo AND t.MaterialId=m.MaterialId JOIN dbo.PURC_PURCHASE_REQUEST f ON f.PRNo=t.PRNo AND f.MaterialId=t.MaterialId`)).recordset[0] as Record<string, number>;
  const report = { generatedAt: new Date().toISOString(), finalPr: { schema: finalSchema, quality: finalQuality }, tempToFinal: { coarsePrMaterial: tempFinal, linePrItemMaterial: tempFinalItem }, mrpToTemp: mrpTemp, mrpDuplicates: duplicateM, uom, decisions: { finalPrQuantitySource: 'dbo.PURC_PURCHASE_REQUEST.Qty', finalPrQuantityConfidence: 'PROBABLE', tempFinalLineMappingValidated: false, coverageGrainValidated: false, fanoutControlled: false, nullAsZeroSafe: false, uomCompatible: 'UNKNOWN', prCreatedQuantityQueryable: false, runtimeJoinAllowed: false, remainingQuantitySafe: false }, security: { rawRowsPersisted: false, databaseMutation: false, geminiInvolved: false } };
  await mkdir(root, { recursive: true }); await writeFile(join(root, 'final-pr-coverage-evidence.json'), `${JSON.stringify(report, null, 2)}\n`); console.log(JSON.stringify({ finalPr: report.finalPr.quality, tempToFinal: report.tempToFinal, mrpToTemp: report.mrpToTemp, duplicates: report.mrpDuplicates, uom: report.uom, decisions: report.decisions }, null, 2));
} finally { await closeSqlServer(); }
