import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { closeSqlServer, getSqlServerPool } from '../src/config/sqlserver.js';

const root = join(process.cwd(), '..', 'semantic', 'catalog'); const pool = await getSqlServerPool();
function errorMeta(error: unknown) { const value = error as { number?: unknown; code?: unknown; message?: unknown }; return { errorNumber: value.number, errorCode: value.code, messageClass: typeof value.message === 'string' ? value.message.split(':')[0] : 'SQL_ERROR' }; }
try {
  const bpiSchema = (await pool.request().query(`SELECT c.name AS column_name,t.name AS datatype,c.max_length,c.precision,c.scale,c.is_nullable,c.is_identity,c.is_computed,CASE WHEN pk.column_id IS NULL THEN 0 ELSE 1 END AS is_pk,CASE WHEN fk.parent_column_id IS NULL THEN 0 ELSE 1 END AS is_fk FROM sys.columns c JOIN sys.objects o ON o.object_id=c.object_id JOIN sys.types t ON t.user_type_id=c.user_type_id LEFT JOIN (SELECT ic.object_id,ic.column_id FROM sys.index_columns ic JOIN sys.indexes i ON i.object_id=ic.object_id AND i.index_id=ic.index_id WHERE i.is_primary_key=1) pk ON pk.object_id=c.object_id AND pk.column_id=c.column_id LEFT JOIN sys.foreign_key_columns fk ON fk.parent_object_id=c.object_id AND fk.parent_column_id=c.column_id WHERE SCHEMA_NAME(o.schema_id)='dbo' AND o.name='BPI_MR' ORDER BY c.column_id`)).recordset;
  const definition = (await pool.request().query<{ definition: string }>(`SELECT m.definition FROM sys.sql_modules m JOIN sys.objects o ON o.object_id=m.object_id WHERE SCHEMA_NAME(o.schema_id)='dbo' AND o.name='PURCV_BP_PR'`)).recordset[0]?.definition ?? '';
  const base = { source: 'dbo.BPI_MR', temp: 'dbo.PURC_PURCHREQUEST_TEMP', final: 'dbo.PURC_PURCHASE_REQUEST' };
  const bpiAgg = (await pool.request().query(`SELECT COUNT_BIG(*) AS bpi_rows,COUNT(DISTINCT CONCAT(ISNULL(NO_MR,''),'|',ISNULL(CONVERT(varchar(100),KD_BARANG),''))) AS distinct_no_mr_material,COUNT(DISTINCT CONCAT(ISNULL(NO_MR,''),'|',ISNULL(CONVERT(varchar(100),KD_BARANG),''),'|',ISNULL(CONVERT(varchar(100),QTY),''))) AS distinct_with_qty,COUNT(DISTINCT NO_MR) AS distinct_no_mr,COUNT(DISTINCT KD_BARANG) AS distinct_material FROM dbo.BPI_MR`)).recordset[0] as Record<string, number>;
  const bpiTemp = (await pool.request().query(`WITH g AS (SELECT b.NO_MR,b.KD_BARANG,COUNT_BIG(*) AS n FROM dbo.BPI_MR b LEFT JOIN dbo.PURC_PURCHREQUEST_TEMP t ON t.PRNo=b.NO_MR AND t.MaterialId=b.KD_BARANG GROUP BY b.NO_MR,b.KD_BARANG) SELECT SUM(CASE WHEN n=0 THEN 1 ELSE 0 END) AS no_match,SUM(CASE WHEN n=1 THEN 1 ELSE 0 END) AS one_match,SUM(CASE WHEN n>1 THEN 1 ELSE 0 END) AS multiple_bpi_groups,MAX(n) AS max_n FROM (SELECT b.NO_MR,b.KD_BARANG,COUNT(t.Id) AS n FROM dbo.BPI_MR b LEFT JOIN dbo.PURC_PURCHREQUEST_TEMP t ON t.PRNo=b.NO_MR AND t.MaterialId=b.KD_BARANG GROUP BY b.NO_MR,b.KD_BARANG) g`)).recordset[0] as Record<string, number>;
  const tempFinal = (await pool.request().query(`WITH g AS (SELECT t.PRNo,t.MaterialId,t.ItemNo,COUNT(f.PRNo) AS n FROM dbo.PURC_PURCHREQUEST_TEMP t LEFT JOIN dbo.PURC_PURCHASE_REQUEST f ON f.PRNo=t.PRNo AND f.MaterialId=t.MaterialId GROUP BY t.PRNo,t.MaterialId,t.ItemNo) SELECT COUNT_BIG(*) AS temp_lines,SUM(CASE WHEN n=0 THEN 1 ELSE 0 END) AS unmatched,SUM(CASE WHEN n=1 THEN 1 ELSE 0 END) AS one_match,SUM(CASE WHEN n>1 THEN 1 ELSE 0 END) AS many_match,MAX(n) AS max_match FROM g`)).recordset[0] as Record<string, number>;
  const nulls = (await pool.request().query(`SELECT SUM(CASE WHEN v.QtyPr IS NULL AND v.PRNo IS NULL THEN 1 ELSE 0 END) AS null_both,SUM(CASE WHEN v.QtyPr IS NULL AND v.PRNo IS NOT NULL THEN 1 ELSE 0 END) AS null_qtypr_pr_present,SUM(CASE WHEN v.QtyPr IS NOT NULL AND v.PRNo IS NULL THEN 1 ELSE 0 END) AS qtypr_present_pr_null,SUM(CASE WHEN v.QtyPr IS NOT NULL AND v.PRNo IS NOT NULL THEN 1 ELSE 0 END) AS both_present FROM dbo.PURCV_BP_PR v`)).recordset[0] as Record<string, number>;
  const duplicates = (await pool.request().query(`WITH d AS (SELECT MRPNo,MaterialId,DepartId,Tipe,MRPDate,Status,Qty,UoM,COUNT_BIG(*) AS n FROM dbo.PURCH_MRP GROUP BY MRPNo,MaterialId,DepartId,Tipe,MRPDate,Status,Qty,UoM) SELECT SUM(CASE WHEN n>1 THEN 1 ELSE 0 END) AS identical_groups,SUM(CASE WHEN n>1 THEN n ELSE 0 END) AS rows_in_identical_groups,MAX(n) AS max_identical FROM d`)).recordset[0] as Record<string, number>;
  const units = (await pool.request().query(`WITH m AS (SELECT COUNT_BIG(*) AS rows,SUM(CASE WHEN LTRIM(RTRIM(UoM))=LTRIM(RTRIM(UoM)) THEN 1 ELSE 0 END) AS same FROM dbo.PURCH_MRP WHERE UoM IS NOT NULL), p AS (SELECT COUNT_BIG(*) AS rows FROM dbo.BPI_MR) SELECT m.rows AS mrp_rows,m.same AS mrp_uom_present,p.rows AS bpi_rows FROM m CROSS JOIN p`)).recordset[0] as Record<string, number>;
  const report = { generatedAt: new Date().toISOString(), schema: { BPI_MR: bpiSchema }, lineage: { source: 'dbo.BPI_MR.QTY', mrpReference: 'dbo.BPI_MR.NO_MR', material: 'dbo.BPI_MR.KD_BARANG', prNumber: 'dbo.PURC_PURCHREQUEST_TEMP.PRNo', sqlModuleReferenceCount: (definition.match(/QtyPr|NO_MR|KD_BARANG|PURC_PURCHASE_REQUEST/gi) ?? []).length }, base, aggregates: { bpi: bpiAgg, bpiToTemp: bpiTemp, tempToFinal: tempFinal, viewNulls: nulls, mrpDuplicates: duplicates, units }, decisions: { lineageValidated: true, grainValidated: false, fanoutControlled: false, nullAsZeroSafe: false, unitCompatible: 'UNKNOWN', prCreatedQuantityQueryable: false, runtimeJoinAllowed: false, remainingQuantitySafe: false }, security: { rawRowsPersisted: false, databaseMutation: false, geminiInvolved: false } };
  await mkdir(root, { recursive: true }); await writeFile(join(root, 'mrp-pr-base-object-evidence.json'), `${JSON.stringify(report, null, 2)}\n`); console.log(JSON.stringify({ bpi: report.aggregates.bpi, bpiToTemp: report.aggregates.bpiToTemp, tempToFinal: report.aggregates.tempToFinal, nulls: report.aggregates.viewNulls, decisions: report.decisions }, null, 2));
} catch (error) { console.log(JSON.stringify({ status: 'ERROR', error: errorMeta(error) }, null, 2)); process.exitCode = 1; } finally { await closeSqlServer(); }
