import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { closeSqlServer, getSqlServerPool } from '../src/config/sqlserver.js';

type CatalogObject = { schemaName: string; objectName: string; objectType: string; columns?: Array<{ columnName: string; datatype: string; nullable?: string }> };
type DefinitionRow = { schemaName: string; objectName: string; typeDescription: string; definition: string };
const root = join(process.cwd(), '..', 'semantic', 'catalog');
const catalog = JSON.parse(await readFile(join(root, 'schema.json'), 'utf8')) as { objects: CatalogObject[] };
const quote = (value: string) => `[${value.replace(/]/g, ']]')}]`;
const qObject = (schemaName: string, objectName: string) => `${quote(schemaName)}.${quote(objectName)}`;
function errorMeta(error: unknown, object?: string, column?: string) { const value = error as { number?: unknown; code?: unknown; name?: unknown; class?: unknown; state?: unknown; message?: unknown }; return { object, column, errorNumber: typeof value.number === 'number' ? value.number : undefined, errorCode: typeof value.code === 'string' ? value.code : undefined, errorClass: typeof value.class === 'number' ? value.class : undefined, errorState: typeof value.state === 'number' ? value.state : undefined, errorName: typeof value.name === 'string' ? value.name : 'SQL_ERROR', errorMessageClass: typeof value.message === 'string' ? value.message.split(':')[0].slice(0, 160) : 'SQL_ERROR' }; }
function references(definition: string) { const terms = ['MRP', 'MRP_TMP', 'PURCH_MRP', 'PURCH_MRP_MONTHLY', 'PURCH_MRP_YEAR', 'QtyPR', 'PURC_PURCHREQUEST_TEMP', 'PURC_PURCHASE_REQUEST', 'MRPNo', 'MaterialId', 'Dept', 'Requestor', 'Status_Info', 'Approval_Info']; return terms.filter((term) => definition.toLowerCase().includes(term.toLowerCase())); }
function operations(definition: string) { return { select: /\bSELECT\b/i.test(definition), insert: /\bINSERT\b/i.test(definition), update: /\bUPDATE\b/i.test(definition), delete: /\bDELETE\b/i.test(definition), join: /\bJOIN\b/i.test(definition), case: /\bCASE\b/i.test(definition), arithmeticQty: /(?:Qty\s*[+-/*]|QtyPR\s*[+-/*]|[+-/*]\s*QtyPR)/i.test(definition) }; }
function snippets(definition: string, term: string) { const output: string[] = []; const regex = new RegExp(`.{0,180}${term}.{0,260}`, 'gi'); for (const match of definition.matchAll(regex)) output.push(match[0].replace(/\s+/g, ' ').trim().slice(0, 500)); return [...new Set(output)].slice(0, 10); }
const pool = await getSqlServerPool();
try {
  const definitionResult = await pool.request().query<DefinitionRow>(`SELECT OBJECT_SCHEMA_NAME(m.object_id) AS schemaName,o.name AS objectName,o.type_desc AS typeDescription,m.definition FROM sys.sql_modules m JOIN sys.objects o ON o.object_id=m.object_id WHERE m.definition LIKE '%MRP%' OR m.definition LIKE '%QtyPR%' OR m.definition LIKE '%PURC_PURCHREQUEST_TEMP%' OR m.definition LIKE '%PURC_PURCHASE_REQUEST%'`);
  const definitions = definitionResult.recordset.map((row) => ({ object: `${row.schemaName}.${row.objectName}`, type: row.typeDescription, operations: operations(row.definition), references: references(row.definition), qtyPrContexts: snippets(row.definition, 'QtyPR'), mrpNoContexts: snippets(row.definition, 'MRPNo'), relevantLogic: snippets(row.definition, 'MRP') }));
  const bp = definitions.find((item) => item.object.toUpperCase() === 'DBO.PURCV_BP_PR');
  const mrpNames = ['MRP', 'MRP_TMP', 'PURCH_MRP', 'PURCH_MRP_MONTHLY', 'PURCH_MRP_YEAR', 'PURCH_MRP_NOTE', 'PURCH_MRP_OVERTIME', 'PURCH_MRP_OVERTIMEHEAD', 'PURCH_MRP_TOTAL_GROUPNAME', 'forecast'];
  const mrpObjects = catalog.objects.filter((object) => object.schemaName === 'dbo' && mrpNames.some((name) => name.toLowerCase() === object.objectName.toLowerCase()));
  async function population(object: CatalogObject) { try { const row = (await pool.request().query(`SELECT COUNT_BIG(*) AS row_count FROM ${qObject(object.schemaName, object.objectName)}`)).recordset[0] as { row_count?: number }; return { status: 'AVAILABLE', rowCount: Number(row.row_count ?? 0) }; } catch (error) { return { status: 'ERROR', error: errorMeta(error, `${object.schemaName}.${object.objectName}`) }; } }
  const populations = await Promise.all(mrpObjects.map(async (object) => ({ object: `${object.schemaName}.${object.objectName}`, type: object.objectType, population: await population(object), codeReferenceCount: definitions.filter((item) => item.references.some((reference) => reference.toLowerCase() === object.objectName.toLowerCase())).length, candidateRole: /MONTHLY/i.test(object.objectName) ? 'MONTHLY_AGGREGATE' : /YEAR/i.test(object.objectName) ? 'YEARLY_AGGREGATE' : /TMP/i.test(object.objectName) ? 'TEMP_WORKFLOW' : /NOTE/i.test(object.objectName) ? 'NOTE' : /OVERTIME/i.test(object.objectName) ? 'OVERTIME' : 'MRP_OR_PLANNING_CANDIDATE' })));
  const columnsResult = await pool.request().query<{ schemaName: string; objectName: string; columnName: string; datatype: string; nullable: string }>(`SELECT s.name AS schemaName,o.name AS objectName,c.name AS columnName,t.name AS datatype,c.is_nullable AS nullable FROM sys.columns c JOIN sys.objects o ON o.object_id=c.object_id JOIN sys.schemas s ON s.schema_id=o.schema_id JOIN sys.types t ON t.user_type_id=c.user_type_id WHERE o.is_ms_shipped=0 AND (c.name LIKE '%MaterialId%' OR c.name LIKE '%MaterialID%' OR c.name LIKE '%MaterialCode%' OR c.name LIKE '%MaterialNo%' OR c.name LIKE '%MatId%' OR c.name LIKE '%PartNo%' OR c.name LIKE '%ItemCode%') ORDER BY s.name,o.name,c.column_id`);
  const materialCandidates = columnsResult.recordset.map((row) => ({ schema: row.schemaName, object: row.objectName, column: row.columnName, datatype: row.datatype, nullable: row.nullable }));
  const mrpMaterialColumns = mrpObjects.flatMap((object) => (object.columns ?? []).filter((column) => /material.?id|material.?code|material.?no|matid|partno|itemcode/i.test(column.columnName)).map((column) => ({ object: `${object.schemaName}.${object.objectName}`, column: column.columnName })));
  async function match(source: { object: string; column: string }, target: { schema: string; object: string; column: string }) { try { const sourceParts = source.object.split('.'); const sourceSql = qObject(sourceParts[0], sourceParts[1]); const targetSql = qObject(target.schema, target.object); const query = `WITH s AS (SELECT TOP (@limit) NULLIF(LTRIM(RTRIM(CONVERT(nvarchar(255),${quote(source.column)}))),'') AS value FROM ${sourceSql} WHERE ${quote(source.column)} IS NOT NULL), t AS (SELECT DISTINCT NULLIF(LTRIM(RTRIM(CONVERT(nvarchar(255),${quote(target.column)}))),'') AS value FROM ${targetSql} WHERE ${quote(target.column)} IS NOT NULL), m AS (SELECT CASE WHEN t.value IS NULL THEN 0 ELSE 1 END AS matched FROM s LEFT JOIN t ON t.value=s.value) SELECT COUNT_BIG(*) AS sampled,SUM(matched) AS matched FROM m`; const row = (await pool.request().input('limit', 10000).query(query)).recordset[0] as Record<string, unknown>; const sampled = Number(row.sampled ?? 0); const matched = Number(row.matched ?? 0); return { source: `${source.object}.${source.column}`, target: `${target.schema}.${target.object}.${target.column}`, status: 'AVAILABLE', sampled, matched, unmatched: sampled - matched, matchRate: sampled ? matched / sampled : 0, confidence: sampled && matched / sampled >= 0.99 ? 'CONFIRMED_BY_DATA' : 'UNKNOWN' }; } catch (error) { return { source: `${source.object}.${source.column}`, target: `${target.schema}.${target.object}.${target.column}`, status: 'ERROR', error: errorMeta(error, `${target.schema}.${target.object}`, target.column) }; } }
  const relationshipResults = []; for (const source of mrpMaterialColumns) { for (const target of materialCandidates.filter((candidate) => candidate.object !== source.object.split('.')[1]).slice(0, 40)) relationshipResults.push(await match(source, target)); }
  const report = { generatedAt: new Date().toISOString(), connection: { status: 'PASS', database: process.env.SQLSERVER_DATABASE ?? 'configured', serverReachable: true }, security: { rawRowsPersisted: false, databaseMutation: false, geminiInvolved: false }, PURCV_BP_PR: { definitionInspected: Boolean(bp), definition: bp ?? null, whatItProves: bp?.references ?? [], whatItDoesNotProve: ['Field business meanings are not promoted from references alone', 'MRP-to-PR runtime join remains blocked without validated key/rule'] }, definitions, sourceRanking: populations, materialColumnCandidates: materialCandidates, mrpMaterialColumns, materialRelationships: relationshipResults, MRPNo: { status: 'CODE_REFERENCES_COLLECTED', directValidatedRelationship: false }, QtyPR: { status: definitions.some((item) => item.qtyPrContexts.length > 0) ? 'REFERENCES_FOUND_MEANING_UNRESOLVED' : 'NOT_REFERENCED', arithmeticEvidence: definitions.some((item) => item.operations.arithmeticQty) }, promotion: { entity: 'material_requirement', queryable: false, blockers: ['Quantity semantics unresolved', 'MRPDate business meaning unresolved', 'MRP-to-PR relationship unresolved', 'MRP-to-inventory relationship unresolved'] } };
  await mkdir(root, { recursive: true }); await writeFile(join(root, 'mrp-pr-view-analysis.json'), `${JSON.stringify(report, null, 2)}\n`); console.log(JSON.stringify({ connection: report.connection, bpDefinitionInspected: report.PURCV_BP_PR.definitionInspected, definitionCount: report.definitions.length, sourceCount: report.sourceRanking.length, materialCandidates: report.materialColumnCandidates.length, relationshipChecks: report.materialRelationships.length, queryable: report.promotion.queryable }, null, 2));
} finally { await closeSqlServer(); }
