import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { closeSqlServer, getSqlServerPool } from '../src/config/sqlserver.js';

const root = join(process.cwd(), '..', 'semantic', 'catalog');
const pool = await getSqlServerPool();
try {
  const patternResult = await pool.request().query(`WITH x AS (SELECT MRPDate, LTRIM(RTRIM(MRPDate)) AS trimmed, REPLACE(REPLACE(REPLACE(LTRIM(RTRIM(MRPDate)),CHAR(13),''),CHAR(10),''),CHAR(9),'') AS cleaned FROM dbo.PURCH_MRP), p AS (SELECT CASE WHEN MRPDate IS NULL THEN 'NULL' WHEN MRPDate LIKE '%'+CHAR(13)+'%' OR MRPDate LIKE '%'+CHAR(10)+'%' OR MRPDate LIKE '%'+CHAR(9)+'%' THEN 'HIDDEN_CONTROL_CHAR' WHEN LEN(trimmed)<>LEN(MRPDate) THEN 'LEADING_OR_TRAILING_SPACE' WHEN LEN(cleaned)=10 AND cleaned LIKE '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]' THEN 'YYYY-MM-DD' WHEN LEN(cleaned)=10 AND cleaned LIKE '[0-9][0-9]/[0-9][0-9]/[0-9][0-9][0-9][0-9]' THEN 'DD_OR_MM_SLASH_YYYY' WHEN LEN(cleaned)=10 AND cleaned LIKE '[0-9][0-9]-[0-9][0-9]-[0-9][0-9][0-9][0-9]' THEN 'DD_OR_MM_DASH_YYYY' WHEN LEN(cleaned)=8 AND cleaned NOT LIKE '%[^0-9]%' THEN 'EIGHT_DIGITS' WHEN LEN(cleaned)=7 AND cleaned LIKE '[0-9][0-9][0-9][0-9]-[0-9][0-9]' THEN 'YYYY-MM' WHEN LEN(cleaned)=7 AND cleaned LIKE '[0-9][0-9]/[0-9][0-9][0-9][0-9]' THEN 'MM-OR-DD-YYYY' WHEN LEN(cleaned)=6 AND cleaned NOT LIKE '%[^0-9]%' THEN 'SIX_DIGITS' ELSE 'OTHER' END AS pattern FROM x) SELECT pattern,COUNT_BIG(*) AS row_count FROM p GROUP BY pattern ORDER BY row_count DESC`);
  const patterns = patternResult.recordset.map((row: Record<string, unknown>) => ({ pattern: row.pattern, count: Number(row.row_count ?? 0) }));
  const parserResult = await pool.request().query(`SELECT COUNT_BIG(*) AS total_non_null,SUM(CASE WHEN MRPDate IS NOT NULL AND TRY_CONVERT(date,REPLACE(LTRIM(RTRIM(MRPDate)),'/','-'),23) IS NOT NULL THEN 1 ELSE 0 END) AS parsed_iso,SUM(CASE WHEN MRPDate IS NOT NULL AND TRY_CONVERT(date,LTRIM(RTRIM(MRPDate)),103) IS NOT NULL THEN 1 ELSE 0 END) AS parsed_103,SUM(CASE WHEN MRPDate IS NOT NULL AND TRY_CONVERT(date,LTRIM(RTRIM(MRPDate)),112) IS NOT NULL THEN 1 ELSE 0 END) AS parsed_112,SUM(CASE WHEN MRPDate IS NOT NULL AND TRY_CONVERT(date,LTRIM(RTRIM(MRPDate)),23) IS NOT NULL THEN 1 ELSE 0 END) AS parsed_23 FROM dbo.PURCH_MRP`);
  const parsers = parserResult.recordset[0] as Record<string, number>;
  const rangeResult = await pool.request().query(`WITH p AS (SELECT COALESCE(TRY_CONVERT(date,REPLACE(LTRIM(RTRIM(MRPDate)),'/','-'),23),TRY_CONVERT(date,LTRIM(RTRIM(MRPDate)),103),TRY_CONVERT(date,LTRIM(RTRIM(MRPDate)),112)) AS d FROM dbo.PURCH_MRP) SELECT MIN(d) AS min_date,MAX(d) AS max_date,COUNT(d) AS parsed_count FROM p WHERE d IS NOT NULL`);
  const range = rangeResult.recordset[0] as Record<string, unknown>;
  const total = Number(parsers.total_non_null ?? 0); const parsedAfter = Number(range.parsed_count ?? 0); const report = { generatedAt: new Date().toISOString(), source: 'dbo.PURCH_MRP.MRPDate', totalRows: 37947, nullRows: 37947 - total, patterns, hiddenCharacterIssue: patterns.some((item) => ['HIDDEN_CONTROL_CHAR', 'LEADING_OR_TRAILING_SPACE'].includes(String(item.pattern))), parsing: { parsedBefore: 1689, coverageBefore: 1689 / total, parsedAfter, coverageAfter: total ? parsedAfter / total : 0, unparsedCount: total - parsedAfter, strategies: ['TRY_CONVERT(style 23) after normalized separators', 'TRY_CONVERT(style 103)', 'TRY_CONVERT(style 112)'], minDate: range.min_date ?? null, maxDate: range.max_date ?? null, queryable: total > 0 && parsedAfter / total >= 0.99 }, semantics: { meaning: 'Tanggal MRP dibuat', confidence: 'CONFIRMED_BY_HUMAN', physicalParserValidated: parsedAfter / total >= 0.99, queryable: total > 0 && parsedAfter / total >= 0.99 }, security: { rawRowsPersisted: false, databaseMutation: false, geminiInvolved: false } };
  await mkdir(root, { recursive: true }); await writeFile(join(root, 'mrp-date-format-evidence.json'), `${JSON.stringify(report, null, 2)}\n`); console.log(JSON.stringify(report, null, 2));
} finally { await closeSqlServer(); }
