import { readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { getSqlServerPool, closeSqlServer } from '../src/config/sqlserver.js';
import { normalizeType, profilePlan } from '../src/semantic/profile.js';

function numberOrNull(value: unknown) { return value === null || value === undefined ? null : Number(value); }
function resultFor(field: { schemaName: string; objectName: string; columnName: string; datatype: string }, plan: { group: string; status: string }, row: Record<string, unknown>) { const rows = numberOrNull(row.rowEstimate); const nullCount = numberOrNull(row.nullCount); const base: Record<string, unknown> = { schema: field.schemaName, object: field.objectName, column: field.columnName, datatype: normalizeType(field.datatype), status: plan.status }; if (plan.status !== 'PROFILED') return base; base.nullRatio = rows && nullCount !== null ? nullCount / rows : null; base.nonNullCount = rows !== null && nullCount !== null ? rows - nullCount : null; if (plan.group === 'NUMERIC') { base.distinctCount = numberOrNull(row.distinctCount); base.numericRange = { min: row.minNumeric ?? null, max: row.maxNumeric ?? null }; } if (plan.group === 'BOOLEAN') base.distinctCount = numberOrNull(row.distinctCount); if (plan.group === 'DATE_TIME') base.dateRange = { min: row.minDate ?? null, max: row.maxDate ?? null }; if (plan.group === 'TIME_ONLY') base.timeRange = { min: row.minTime ?? null, max: row.maxTime ?? null }; if (plan.group === 'STRING') { base.distinctCount = numberOrNull(row.distinctCount); base.minLength = numberOrNull(row.minLength); base.maxLength = numberOrNull(row.maxLength); base.averageLength = numberOrNull(row.averageLength); } if (plan.group === 'IDENTIFIER') base.distinctCount = numberOrNull(row.distinctCount); return base; }
type SchemaObject = { schemaName: string; objectName: string; objectType: string; columns?: Array<{ columnName: string; datatype: string }> };
const root = join(process.cwd(), '..', 'semantic', 'catalog'); const schemaCatalog = JSON.parse(await readFile(join(root, 'schema.json'), 'utf8')) as { objects: SchemaObject[] }; const maxRows = Number(process.env.SEMANTIC_PROFILE_MAX_ROWS ?? 1000000); const timeoutMs = Number(process.env.SEMANTIC_PROFILE_TIMEOUT_MS ?? 10000); const fields = schemaCatalog.objects.flatMap((object) => (object.columns ?? []).map((column) => ({ ...column, schemaName: object.schemaName, objectName: object.objectName, objectType: object.objectType }))); const pool = await getSqlServerPool(); const statistics: Record<string, unknown>[] = []; let attempted = 0; let profiled = 0; let skipped = 0; let failed = 0;
try { for (const field of fields) { attempted += 1; const plan = profilePlan(field.datatype, `${field.schemaName}.${field.objectName}`, field.columnName); if (plan.status !== 'PROFILED') { skipped += 1; statistics.push(resultFor(field, plan, {})); continue; } if (field.objectType === 'VIEW') { skipped += 1; statistics.push({ schema: field.schemaName, object: field.objectName, column: field.columnName, datatype: normalizeType(field.datatype), status: 'SKIPPED_EXPENSIVE_VIEW' }); continue; } try { const request = pool.request(); const result = await request.query(plan.text!); const row = (result.recordset[0] ?? {}) as Record<string, unknown>; const rows = numberOrNull(row.rowEstimate); if (rows !== null && rows > maxRows) { skipped += 1; statistics.push({ schema: field.schemaName, object: field.objectName, column: field.columnName, datatype: normalizeType(field.datatype), status: 'SKIPPED_LARGE_OBJECT', rowEstimate: rows }); continue; } profiled += 1; statistics.push(resultFor(field, plan, row)); } catch (error) { failed += 1; const code = typeof error === 'object' && error && 'number' in error ? Number((error as { number?: number }).number) : undefined; statistics.push({ schema: field.schemaName, object: field.objectName, column: field.columnName, datatype: normalizeType(field.datatype), status: 'PROFILE_ERROR', errorCode: Number.isFinite(code) ? code : null }); } } const summary = { objectsAttempted: new Set(fields.map((field) => `${field.schemaName}.${field.objectName}`)).size, columnsAttempted: attempted, columnsProfiled: profiled, columnsSkipped: skipped, columnsFailed: failed }; const output = { generatedAt: new Date().toISOString(), persisted: 'derived-statistics-only', summary, statistics }; await writeFile(join(root, 'profile.json'), JSON.stringify(output, null, 2)); await writeFile(join(root, 'profile-report.json'), JSON.stringify({ ...output, status: 'COMPLETED' }, null, 2)); console.log(JSON.stringify({ ...summary, rowsPersisted: 0 }, null, 2)); } finally { await closeSqlServer(); }
