import { createInterface } from 'node:readline/promises';
import { stdin as input, stdout as output } from 'node:process';
import { join } from 'node:path';
import { writeFile } from 'node:fs/promises';
import { loadApproved, loadRejected, refreshPending, reviewRoot, writeAudit, type ApprovedReview, type RejectedReview } from '../src/semantic/review.js';

const args = process.argv.slice(2); const state = await refreshPending();
if (args.includes('--non-interactive') || process.env.npm_config_non_interactive === 'true') { console.log(JSON.stringify({ pending: state.pending.length, approved: state.approved.length, rejected: state.rejected.length }, null, 2)); }
else { const rl = createInterface({ input, output }); try { for (const candidate of state.pending) { console.log(`\n${candidate.entity} / ${candidate.semanticField}\n\nPhysical:\n${candidate.physicalSource}\n\nSuggested semantic:\n${candidate.suggestedMeaning}\n\nEvidence:\n${candidate.evidence.map((item) => `- ${item}`).join('\n')}`); const decision = (await rl.question('\nApprove mapping? Y/N/Skip: ')).trim().toUpperCase(); if (decision !== 'Y' && decision !== 'N') continue; const reason = await rl.question(`${decision === 'Y' ? 'Approval' : 'Rejection'} reason: `); const now = new Date().toISOString(); if (decision === 'Y') { const item: ApprovedReview = { ...candidate, approvedMeaning: candidate.suggestedMeaning, confidence: 'CONFIRMED_BY_HUMAN', approvedAt: now, approvalReason: reason }; await writeFile(join(reviewRoot(), 'approved.json'), `${JSON.stringify([...await loadApproved(), item], null, 2)}\n`); await writeAudit('SEMANTIC_MAPPING_APPROVED', { reviewId: candidate.reviewId, entity: candidate.entity, field: candidate.semanticField, decision: 'APPROVED', timestamp: now }); } else { const item: RejectedReview = { ...candidate, rejectedAt: now, rejectionReason: reason }; await writeFile(join(reviewRoot(), 'rejected.json'), `${JSON.stringify([...await loadRejected(), item], null, 2)}\n`); await writeAudit('SEMANTIC_MAPPING_REJECTED', { reviewId: candidate.reviewId, entity: candidate.entity, field: candidate.semanticField, decision: 'REJECTED', timestamp: now }); } } await refreshPending(); } finally { rl.close(); } }
