import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { closeSqlServer, getSqlServerPool } from '../src/config/sqlserver.js';
const root = join(process.cwd(), '..', 'semantic', 'catalog'); const pool = await getSqlServerPool();
try {
  const bridge = (await pool.request().query(`WITH bridge AS (SELECT DISTINCT MRPNo,MaterialId,PRNo FROM dbo.PURC_PURCHREQUEST_TEMP WHERE NULLIF(LTRIM(RTRIM(MRPNo)),'') IS NOT NULL AND MaterialId IS NOT NULL AND NULLIF(LTRIM(RTRIM(PRNo)),'') IS NOT NULL), g AS (SELECT MRPNo,MaterialId,COUNT(*) AS pr_count FROM bridge GROUP BY MRPNo,MaterialId) SELECT (SELECT COUNT(*) FROM dbo.PURC_PURCHREQUEST_TEMP) AS raw_temp,(SELECT COUNT(*) FROM bridge) AS bridge_rows,(SELECT COUNT(*) FROM g) AS coverage_groups,SUM(CASE WHEN pr_count=1 THEN 1 ELSE 0 END) AS one_pr,SUM(CASE WHEN pr_count>1 THEN 1 ELSE 0 END) AS many_pr,MAX(pr_count) AS max_pr FROM g`)).recordset[0] as Record<string, number>;
  const finalGroup = (await pool.request().query(`WITH g AS (SELECT PRNo,MaterialId,COUNT_BIG(*) AS physical_rows,SUM(Qty) AS final_qty,COUNT(DISTINCT UoM) AS uom_count,SUM(CASE WHEN Qty IS NULL THEN 1 ELSE 0 END) AS null_qty FROM dbo.PURC_PURCHASE_REQUEST GROUP BY PRNo,MaterialId) SELECT COUNT_BIG(*) AS groups,SUM(CASE WHEN physical_rows=1 THEN 1 ELSE 0 END) AS one_physical,SUM(CASE WHEN physical_rows>1 THEN 1 ELSE 0 END) AS many_physical,MAX(physical_rows) AS max_physical,SUM(CASE WHEN uom_count>1 THEN 1 ELSE 0 END) AS multiple_uom_groups,SUM(CASE WHEN null_qty>0 THEN 1 ELSE 0 END) AS null_qty_groups FROM g`)).recordset[0] as Record<string, number>;
  const coverage = (await pool.request().query(`WITH bridge AS (SELECT DISTINCT MRPNo,MaterialId,PRNo FROM dbo.PURC_PURCHREQUEST_TEMP WHERE NULLIF(LTRIM(RTRIM(MRPNo)),'') IS NOT NULL AND MaterialId IS NOT NULL AND NULLIF(LTRIM(RTRIM(PRNo)),'') IS NOT NULL), final_group AS (SELECT PRNo,MaterialId,SUM(Qty) AS final_qty FROM dbo.PURC_PURCHASE_REQUEST GROUP BY PRNo,MaterialId), coverage AS (SELECT b.MRPNo,b.MaterialId,COUNT(DISTINCT b.PRNo) AS pr_count,SUM(f.final_qty) AS created_qty FROM bridge b JOIN final_group f ON f.PRNo=b.PRNo AND f.MaterialId=b.MaterialId GROUP BY b.MRPNo,b.MaterialId) SELECT COUNT_BIG(*) AS matched_groups,SUM(CASE WHEN pr_count>0 THEN 1 ELSE 0 END) AS groups_with_final,MAX(pr_count) AS max_pr_per_group FROM coverage`)).recordset[0] as Record<string, number>;
  const uom = (await pool.request().query(`WITH bridge AS (SELECT DISTINCT MRPNo,MaterialId,PRNo FROM dbo.PURC_PURCHREQUEST_TEMP WHERE NULLIF(LTRIM(RTRIM(MRPNo)),'') IS NOT NULL AND MaterialId IS NOT NULL AND NULLIF(LTRIM(RTRIM(PRNo)),'') IS NOT NULL), rows AS (SELECT b.MRPNo,b.MaterialId,m.UoM AS mrp_uom,f.UoM AS pr_uom FROM bridge b JOIN dbo.PURCH_MRP m ON m.MRPNo=b.MRPNo AND m.MaterialId=b.MaterialId JOIN dbo.PURC_PURCHASE_REQUEST f ON f.PRNo=b.PRNo AND f.MaterialId=b.MaterialId) SELECT COUNT_BIG(*) AS rows,SUM(CASE WHEN mrp_uom IS NULL OR pr_uom IS NULL THEN 1 ELSE 0 END) AS null_uom,SUM(CASE WHEN UPPER(LTRIM(RTRIM(mrp_uom)))=UPPER(LTRIM(RTRIM(pr_uom))) THEN 1 ELSE 0 END) AS same_uom,SUM(CASE WHEN mrp_uom IS NOT NULL AND pr_uom IS NOT NULL AND UPPER(LTRIM(RTRIM(mrp_uom)))<>UPPER(LTRIM(RTRIM(pr_uom))) THEN 1 ELSE 0 END) AS different_uom FROM rows`)).recordset[0] as Record<string, number>;
  const report = { generatedAt: new Date().toISOString(), developerConfirmation: { relation: 'TEMP.PRNo + TEMP.MaterialId = FINAL.PRNo + FINAL.MaterialId', confidence: 'CONFIRMED_BY_HUMAN', evidenceType: 'APPLICATION_DEVELOPER_CONFIRMATION', finalState: 'PURC_PURCHASE_REQUEST represents processed/final PR' }, tempBridge: bridge, finalPrGroup: finalGroup, coverage, uom, decision: { finalPrQuantitySource: 'dbo.PURC_PURCHASE_REQUEST.Qty', finalPrQuantityMeaning: 'final PR quantity', finalPrAggregationSafe: Number(finalGroup.multiple_uom_groups ?? 0) === 0 && Number(finalGroup.null_qty_groups ?? 0) === 0, bridgeSafe: Number(bridge.bridge_rows ?? 0) > 0, fanoutControlled: true, prCreatedQuantityQueryable: false, runtimeJoinAllowed: false, nullAsZeroSafe: false, remainingQuantitySafe: false }, security: { rawRowsPersisted: false, databaseMutation: false, geminiInvolved: false } };
  await mkdir(root, { recursive: true }); await writeFile(join(root, 'canonical-final-pr-coverage-evidence.json'), `${JSON.stringify(report, null, 2)}\n`); console.log(JSON.stringify(report, null, 2));
} finally { await closeSqlServer(); }
