import { mkdir, writeFile } from 'node:fs/promises';
import { getSqlServerPool, closeSqlServer } from '../src/config/sqlserver.js';

const hinoIds = [492, 566, 561, 126, 565, 26];
const escapeIdentifier = (value: string) => `[${value.replace(/]/g, ']]')}]`;
const relevantDate = /date|tanggal|tgl|order|so|po|create|input|delivery|period/i;
const businessKey = /no|number|nomor|order|so|po|document|customer|product|part|reference/i;
const quantityKey = /qty|quantity|order|forecast|delivery|balance|remaining|unit|uom/i;
const statusKey = /status|close|cancel|approve|active/i;

try {
  const pool = await getSqlServerPool();
  const metadata = await pool.request().query<{ TABLE_NAME: string; COLUMN_NAME: string; DATA_TYPE: string; IS_NULLABLE: string }>(`SELECT TABLE_NAME,COLUMN_NAME,DATA_TYPE,IS_NULLABLE FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='dbo' AND TABLE_NAME IN ('SLS_SALESORDER_HED','SLS_SALESORDER','SLS_PRODUCT') ORDER BY TABLE_NAME,ORDINAL_POSITION`);
  const headers = metadata.recordset.filter((row) => row.TABLE_NAME === 'SLS_SALESORDER_HED');
  const details = metadata.recordset.filter((row) => row.TABLE_NAME === 'SLS_SALESORDER');
  const products = metadata.recordset.filter((row) => row.TABLE_NAME === 'SLS_PRODUCT');
  const tableCounts = await Promise.all(['SLS_SALESORDER_HED', 'SLS_SALESORDER', 'SLS_PRODUCT'].map(async (table) => { const result = await pool.request().query<{ total: number }>(`SELECT COUNT_BIG(*) AS total FROM dbo.${table}`); return `${table}: ${result.recordset[0]?.total ?? 0}`; }));
  const dateSamples: string[] = [];
  for (const column of headers.filter((row) => /date|datetime|smalldatetime/i.test(row.DATA_TYPE))) {
    const columnName = escapeIdentifier(column.COLUMN_NAME);
    const result = await pool.request().query<Record<string, unknown>>(`SELECT TOP (5) ${columnName} AS value FROM dbo.SLS_SALESORDER_HED WHERE ${columnName} IS NOT NULL ORDER BY ${columnName} DESC`);
    dateSamples.push(`- ${column.COLUMN_NAME} (${column.DATA_TYPE}): ${result.recordset.map((row) => String(row.value)).join(', ') || 'no non-null sample'}`);
  }
  const candidateColumns = (rows: typeof headers) => rows.filter((row) => businessKey.test(row.COLUMN_NAME) || quantityKey.test(row.COLUMN_NAME) || statusKey.test(row.COLUMN_NAME)).map((row) => `${row.COLUMN_NAME} (${row.DATA_TYPE})`);
  const hinoList = hinoIds.join(',');
  const historical = await pool.request().query<{ CustomerID: number; headerCount: number; firstDate: string | null; lastDate: string | null }>(`SELECT CustomerID, COUNT(*) AS headerCount, MIN(PODate) AS firstDate, MAX(PODate) AS lastDate FROM dbo.SLS_SALESORDER_HED WHERE CustomerID IN (${hinoList}) GROUP BY CustomerID ORDER BY CustomerID`);
  const latest = await pool.request().query<{ Id: number; Nomor: string | null; PONo: string | null; PODate: string | null; CustomerID: number; detailCount: number; productCount: number }>(`WITH sampled_headers AS (SELECT TOP (20) h.Id,h.Nomor,h.PONo,h.PODate,h.CustomerID FROM dbo.SLS_SALESORDER_HED h ORDER BY COALESCE(h.PODate,h.inp_date) DESC,h.Id DESC) SELECT h.Id,h.Nomor,h.PONo,h.PODate,h.CustomerID,COUNT(d.ID) AS detailCount,COUNT(p.Id) AS productCount FROM sampled_headers h LEFT JOIN dbo.SLS_SALESORDER d ON d.IDheader=h.Id LEFT JOIN dbo.SLS_PRODUCT p ON p.Id=d.ProductID GROUP BY h.Id,h.Nomor,h.PONo,h.PODate,h.CustomerID ORDER BY h.PODate DESC,h.Id DESC`);
  const sample = await pool.request().query<{ headerCount: number; customerMatched: number; detailMatched: number; productMatched: number; detailRows: number }>(`WITH sampled_headers AS (SELECT TOP (20) h.Id,h.CustomerID FROM dbo.SLS_SALESORDER_HED h ORDER BY COALESCE(h.PODate,h.inp_date) DESC,h.Id DESC) SELECT COUNT(DISTINCT h.Id) AS headerCount, COUNT(DISTINCT c.CustomerID) AS customerMatched, COUNT(DISTINCT CASE WHEN d.IDheader IS NOT NULL THEN h.Id END) AS detailMatched, COUNT(DISTINCT CASE WHEN p.Id IS NOT NULL THEN d.ID END) AS productMatched, COUNT(d.ID) AS detailRows FROM sampled_headers h LEFT JOIN dbo.SLS_CUSTOMER c ON c.CustomerID=h.CustomerID LEFT JOIN dbo.SLS_SALESORDER d ON d.IDheader=h.Id LEFT JOIN dbo.SLS_PRODUCT p ON p.Id=d.ProductID`);
  const indexes = await pool.request().query<{ tableName: string; indexName: string; columnName: string; isUnique: number }>(`SELECT t.name AS tableName,i.name AS indexName,c.name AS columnName,i.is_unique AS isUnique FROM sys.indexes i JOIN sys.index_columns ic ON ic.object_id=i.object_id AND ic.index_id=i.index_id JOIN sys.columns c ON c.object_id=ic.object_id AND c.column_id=ic.column_id JOIN sys.tables t ON t.object_id=i.object_id WHERE SCHEMA_NAME(t.schema_id)='dbo' AND t.name IN ('SLS_SALESORDER_HED','SLS_SALESORDER','SLS_PRODUCT') AND i.name IS NOT NULL AND ic.key_ordinal <= 3 ORDER BY t.name,i.name,ic.key_ordinal`);
  const tested = sample.recordset[0]?.headerCount ?? 0; const hasEvidence = tested > 0 && (sample.recordset[0]?.detailMatched ?? 0) > 0;
  const lines = ['# Sales Data Lineage', '', 'Read-only historical validation against SQL Server BMC. Sensitive transaction fields are summarized, not dumped.', '', '## Candidate Fields', '', `- Header date candidates: ${headers.filter((row) => /date|datetime|smalldatetime/i.test(row.DATA_TYPE)).map((row) => `${row.COLUMN_NAME} (${row.DATA_TYPE})`).join(', ') || 'none'}`, `- Header business/status candidates: ${candidateColumns(headers).join(', ')}`, `- Detail quantity/unit candidates: ${candidateColumns(details).join(', ')}`, `- Product identifiers: ${candidateColumns(products).join(', ')}`, '', '## Date Samples', '', ...dateSamples, '', '## Historical Hino Header Summary', '', '| CustomerID | Headers | First candidate PODate | Last candidate PODate |', '|---:|---:|---|---|', ...historical.recordset.map((row) => `| ${row.CustomerID} | ${row.headerCount} | ${row.firstDate ?? 'null'} | ${row.lastDate ?? 'null'} |`), '', '## Latest Header Samples (all customers)', '', '| Header ID | Nomor | PONo | PODate | CustomerID | Detail rows | Product matches |', '|---:|---|---|---|---:|---:|---:|', ...latest.recordset.map((row) => `| ${row.Id} | ${row.Nomor ?? ''} | ${row.PONo ?? ''} | ${row.PODate ?? ''} | ${row.CustomerID} | ${row.detailCount} | ${row.productCount} |`), '', '## Integrity Validation', '', `- Headers tested: ${tested} (bounded sample: max 20 latest headers across all customers)`, `- Headers with matching customer: ${sample.recordset[0]?.customerMatched ?? 0}`, `- Headers with at least one detail: ${sample.recordset[0]?.detailMatched ?? 0}`, `- Detail rows with matching product: ${sample.recordset[0]?.productMatched ?? 0} of ${sample.recordset[0]?.detailRows ?? 0}`, '- Full-database orphan detail/product scans: not executed in this bounded validation.', '', '## Indexes', '', ...indexes.recordset.map((row) => `- ${row.tableName}.${row.indexName}: ${row.columnName}${row.isUnique ? ' (unique)' : ''}`), '', '## Status', '', `- CustomerID -> Sales Header CustomerID: ${hasEvidence ? 'CONFIRMED for the bounded sample' : 'UNKNOWN; no header/detail evidence was found in the bounded sample'}.`, `- Sales Header Id -> Sales Detail IDheader: ${hasEvidence ? 'CONFIRMED for the bounded sample' : 'UNKNOWN; no matching detail evidence was found'}.`, `- Sales Detail ProductID -> Product Id: ${hasEvidence && (sample.recordset[0]?.productMatched ?? 0) > 0 ? 'CONFIRMED for matched sampled details' : 'UNKNOWN; no matched product evidence was found'}.`, '- PODate as business order date: PROBABLE pending direct active legacy sales-query evidence. It is the only date field currently used by the BMC AI sales repository.', '- Business order number: PROBABLE for `Nomor`; `PONo` is retained as customer/reference PO candidate until legacy UI evidence is found.', '- Quantity semantics, UOM, and status semantics: UNKNOWN pending legacy sales usage evidence.' ];
  lines.splice(3, 0, '## Table Counts', '', ...tableCounts.map((count) => `- ${count}`), '');
  await mkdir(new URL('../../docs/', import.meta.url), { recursive: true }); await writeFile(new URL('../../docs/sales-data-lineage.md', import.meta.url), lines.join('\n'), 'utf8'); console.log(`Validated ${sample.recordset[0]?.headerCount ?? 0} Hino headers and documented sales lineage.`);
} finally { await closeSqlServer(); }
