import { closeSqlServer, getSqlServerPool } from '../src/config/sqlserver.js';

const pool = await getSqlServerPool();
try {
  const result = await pool.request().query(`WITH groups AS (SELECT DISTINCT MRPNo,MaterialId FROM dbo.PURCH_MRP WHERE NULLIF(LTRIM(RTRIM(MRPNo)),'') IS NOT NULL AND MaterialId IS NOT NULL), bridge AS (SELECT DISTINCT MRPNo,MaterialId,PRNo FROM dbo.PURC_PURCHREQUEST_TEMP WHERE NULLIF(LTRIM(RTRIM(MRPNo)),'') IS NOT NULL AND MaterialId IS NOT NULL AND NULLIF(LTRIM(RTRIM(PRNo)),'') IS NOT NULL), final_pr AS (SELECT DISTINCT PRNo,MaterialId FROM dbo.PURC_PURCHASE_REQUEST WHERE NULLIF(LTRIM(RTRIM(PRNo)),'') IS NOT NULL AND MaterialId IS NOT NULL), counts AS (SELECT g.MRPNo,g.MaterialId,COUNT(DISTINCT b.PRNo) AS released_pr_count,COUNT(DISTINCT CASE WHEN f.PRNo IS NOT NULL THEN b.PRNo END) AS final_pr_count FROM groups g LEFT JOIN bridge b ON b.MRPNo=g.MRPNo AND b.MaterialId=g.MaterialId LEFT JOIN final_pr f ON f.PRNo=b.PRNo AND f.MaterialId=b.MaterialId GROUP BY g.MRPNo,g.MaterialId), classified AS (SELECT *,CASE WHEN final_pr_count > released_pr_count THEN 'DATA_MAPPING_EXCEPTION' WHEN released_pr_count=0 OR final_pr_count=0 THEN 'BELUM_DIBUAT_PR' WHEN final_pr_count<released_pr_count THEN 'SEBAGIAN_DIBUAT_PR' ELSE 'SUDAH_DIBUAT_PR' END AS pr_creation_status FROM counts) SELECT COUNT_BIG(*) AS totalGroups,SUM(CASE WHEN released_pr_count=0 THEN 1 ELSE 0 END) AS noReleasedPr,SUM(CASE WHEN released_pr_count>0 AND final_pr_count=0 THEN 1 ELSE 0 END) AS releasedButNoFinal,SUM(CASE WHEN pr_creation_status='SEBAGIAN_DIBUAT_PR' THEN 1 ELSE 0 END) AS partial,SUM(CASE WHEN pr_creation_status='SUDAH_DIBUAT_PR' THEN 1 ELSE 0 END) AS allFinal,SUM(CASE WHEN pr_creation_status='DATA_MAPPING_EXCEPTION' THEN 1 ELSE 0 END) AS mappingExceptions,SUM(CASE WHEN released_pr_count>1 THEN 1 ELSE 0 END) AS groupsWithMultipleReleasedPr,MAX(released_pr_count) AS maxReleasedPr FROM classified`);
  console.log(JSON.stringify({ semantic: 'material_requirement.pr_creation_status', grain: 'MRPNo + MaterialId', ...result.recordset[0], security: { rawRowsPersisted: false, databaseMutation: false, geminiInvolved: false } }, null, 2));
} finally {
  await closeSqlServer();
}
