import { mkdir, writeFile } from 'node:fs/promises';
import sql from 'mssql';
import { closeSqlServer, getSqlServerPool } from '../src/config/sqlserver.js';

const q = (name: string) => `[${name.replace(/]/g, ']]')}]`;
const hinoId = 5;
const productionPattern = /produksi|production|prd|ppc|plan|casting|furnace|mould|mold|core|trim|shoot|finish|output|actual/i;
const domainColumn = /part|product|material|btno|customer|cust|po|order|qty|quantity|date|tanggal|actual|output|plan|production|mould|mold|uom|unit|satuan|warehouse|location|stock|owner/i;

type Column = { schemaName: string; objectName: string; columnName: string; dataType: string };

try {
  const pool = await getSqlServerPool();
  const meta = await pool.request().query<Column>(`SELECT s.name AS schemaName, o.name AS objectName, c.name AS columnName, t.name AS dataType FROM sys.objects o JOIN sys.schemas s ON s.schema_id=o.schema_id JOIN sys.columns c ON c.object_id=o.object_id JOIN sys.types t ON t.user_type_id=c.user_type_id WHERE o.type IN ('U','V') ORDER BY s.name,o.name,c.column_id`);
  const columns = meta.recordset;
  const byObject = (name: string) => columns.filter((column) => column.schemaName === 'dbo' && column.objectName === name);
  const lines: string[] = ['# Business Link Validation', '', 'Read-only bounded validation. No production formula or database mutation is performed.', ''];

  const sales = await pool.request().query<{ headers: number; customerMatches: number; detailHeaders: number; details: number; productMatches: number; distinctProducts: number }>(`WITH h AS (SELECT TOP (50) Id,CustomerID FROM dbo.SLS_SALESORDER_HED_NEW ORDER BY PODate DESC,Id DESC), d AS (SELECT ID,IDheader,ProductID FROM dbo.SLS_SALESORDER_NEW), hs AS (SELECT h.Id,CASE WHEN c.CustId IS NULL THEN 0 ELSE 1 END AS customerMatch,CASE WHEN EXISTS (SELECT 1 FROM d WHERE d.IDheader=CONVERT(varchar(50),h.Id)) THEN 1 ELSE 0 END AS hasDetail FROM h LEFT JOIN dbo.MAS_CUSTOMER c ON c.CustId=h.CustomerID), ds AS (SELECT DISTINCT d.ID,d.ProductID FROM h JOIN d ON d.IDheader=CONVERT(varchar(50),h.Id)) SELECT COUNT(*) AS headers,SUM(customerMatch) AS customerMatches,SUM(hasDetail) AS detailHeaders,(SELECT COUNT(*) FROM ds) AS details,(SELECT COUNT(*) FROM ds JOIN dbo.MAS_KATALOG_SALES k ON CONVERT(varchar(50),k.Id)=ds.ProductID) AS productMatches,(SELECT COUNT(DISTINCT ProductID) FROM ds) AS distinctProducts FROM hs`);
  lines.push('## Sales 50-Header Validation', '', `- Headers tested: ${sales.recordset[0]?.headers ?? 0}`, `- Customer matches: ${sales.recordset[0]?.customerMatches ?? 0}`, `- Headers with detail: ${sales.recordset[0]?.detailHeaders ?? 0}`, `- Distinct bounded detail rows: ${sales.recordset[0]?.details ?? 0}`, `- Product matches: ${sales.recordset[0]?.productMatches ?? 0}`, `- Distinct products: ${sales.recordset[0]?.distinctProducts ?? 0}`, '- Relationship promotion target: CONFIRMED_BY_DATA only when no contradictory evidence is found.', '');

  const hinoOrders = await pool.request().input('customerId', sql.Int, hinoId).query<{ id: number; nomor: string; poNo: string; poDate: string; productId: string; partNumber: string; quantity: number }>(`SELECT TOP (30) h.Id AS id,h.Nomor AS nomor,h.PONo AS poNo,h.PODate AS poDate,d.ProductID AS productId,d.PartNumber AS partNumber,d.Qty AS quantity FROM dbo.SLS_SALESORDER_HED_NEW h JOIN dbo.SLS_SALESORDER_NEW d ON d.IDheader=CONVERT(varchar(50),h.Id) WHERE h.CustomerID=@customerId ORDER BY h.PODate DESC,h.Id DESC,d.ID`);
  lines.push('## Hino Sales-to-Delivery Investigation', '', `- Hino active customer key: MAS_CUSTOMER.CustId=${hinoId}`, `- Sales detail rows sampled: ${hinoOrders.recordset.length}`);
  for (const row of hinoOrders.recordset.slice(0, 10)) {
    const delivery = await pool.request().input('poNo', sql.NVarChar, row.poNo).input('part', sql.NVarChar, row.partNumber ?? '').query<Record<string, unknown>>(`SELECT TOP (5) h.Id AS deliveryHeaderId,h.Nomor AS deliveryNumber,h.PONo AS deliveryPo,h.Tanggal AS deliveryDate,d.SalesNomor,d.NoPO,d.ProductID,d.Qty AS deliveryQty FROM dbo.SLS_DELIVERYORDER_HED_NEW h JOIN dbo.SLS_DELIVERYORDER_NEW d ON d.HedId=h.Id WHERE h.CustomerID=${hinoId} AND (h.PONo=@poNo OR d.NoPO=@poNo OR d.SalesNomor=@poNo OR d.ProductID=@part) ORDER BY h.Tanggal DESC,h.Id DESC`);
    lines.push(`- Sales order ${row.nomor || '(null)'} / PO ${row.poNo || '(null)'} / part ${row.partNumber || row.productId || '(null)'}: delivery candidates ${delivery.recordset.length}`);
  }
  const deliveryMatch = await pool.request().query<{ salesRows: number; exactPoPartLines: number; poPartLines: number; partOnlyLines: number }>(`WITH sales AS (SELECT DISTINCT h.PONo,d.ID AS salesDetailId,d.ProductID FROM dbo.SLS_SALESORDER_HED_NEW h JOIN dbo.SLS_SALESORDER_NEW d ON d.IDheader=CONVERT(varchar(50),h.Id) WHERE h.CustomerID=${hinoId}), deliveries AS (SELECT DISTINCT h.PONo AS headerPo,d.NoPO AS detailPo,d.ProductID FROM dbo.SLS_DELIVERYORDER_HED_NEW h JOIN dbo.SLS_DELIVERYORDER_NEW d ON d.HedId=h.Id WHERE h.CustomerID=${hinoId}) SELECT (SELECT COUNT(*) FROM sales) AS salesRows,(SELECT COUNT(DISTINCT s.salesDetailId) FROM sales s JOIN deliveries d ON NULLIF(LTRIM(RTRIM(s.PONo)), '')=NULLIF(LTRIM(RTRIM(COALESCE(d.headerPo,d.detailPo))), '') AND CONVERT(varchar(100),s.ProductID)=CONVERT(varchar(100),d.ProductID)) AS exactPoPartLines,(SELECT COUNT(DISTINCT s.salesDetailId) FROM sales s JOIN deliveries d ON NULLIF(LTRIM(RTRIM(s.PONo)), '')=NULLIF(LTRIM(RTRIM(COALESCE(d.headerPo,d.detailPo))), '')) AS poPartLines,(SELECT COUNT(DISTINCT s.salesDetailId) FROM sales s JOIN deliveries d ON CONVERT(varchar(100),s.ProductID)=CONVERT(varchar(100),d.ProductID)) AS partOnlyLines`);
  lines.push(`- Hino Sales detail lines tested: ${deliveryMatch.recordset[0]?.salesRows ?? 0}`, `- Hino lines with exact PO + ProductID delivery candidate: ${deliveryMatch.recordset[0]?.exactPoPartLines ?? 0}`, `- Hino lines with PO delivery candidate: ${deliveryMatch.recordset[0]?.poPartLines ?? 0}`, `- Hino lines with ProductID delivery candidate: ${deliveryMatch.recordset[0]?.partOnlyLines ?? 0}`);
  lines.push('- Exact delivery match requires customer + PO or verified Sales reference + part consistency; date proximity alone is not accepted.', '');

  const deliveryColumns = byObject('SLS_DELIVERYORDER_HED_NEW').concat(byObject('SLS_DELIVERYORDER_NEW'));
  lines.push('## Delivery Semantics Metadata', '', `- Header columns: ${byObject('SLS_DELIVERYORDER_HED_NEW').map((column) => `${column.columnName} (${column.dataType})`).join(', ')}`, `- Detail columns: ${byObject('SLS_DELIVERYORDER_NEW').map((column) => `${column.columnName} (${column.dataType})`).join(', ')}`, '- Confirmed structure: `SLS_DELIVERYORDER_HED_NEW.Id -> SLS_DELIVERYORDER_NEW.HedId`.', '- Delivery business number/date candidates: header `Nomor`, `Tanggal`; `PONo` is customer PO candidate; detail `SalesNomor` is an unconfirmed Sales reference.', '');

  const inventoryObject = columns.find((column) => column.schemaName === 'dbo' && column.objectName === 'SumMatStock');
  const inventoryType = inventoryObject ? await pool.request().input('objectId', sql.Int, 0).query<{ type: string }>(`SELECT CASE WHEN o.type='V' THEN 'VIEW' ELSE 'TABLE' END AS type FROM sys.objects o WHERE o.object_id=OBJECT_ID(N'dbo.SumMatStock')`) : null;
  const inventoryDefinition = inventoryType?.recordset[0]?.type === 'VIEW' ? await pool.request().query<{ definition: string | null }>(`SELECT OBJECT_DEFINITION(OBJECT_ID(N'dbo.SumMatStock')) AS definition`) : null;
  lines.push('## Inventory', '', `- Source: dbo.SumMatStock (${inventoryType?.recordset[0]?.type ?? 'NOT FOUND'})`, `- Columns: ${byObject('SumMatStock').map((column) => `${column.columnName} (${column.dataType})`).join(', ') || 'none'}`, `- View definition available: ${inventoryDefinition?.recordset[0]?.definition ? 'yes' : 'no'}`, '- Quantity semantics: UNKNOWN until view/legacy/transaction evidence identifies whether it is on-hand, physical, available, or summary balance.', '- Dimensions must remain grouped by OwnerId, Stockid, Materialid, and UoM.', '');
  if (inventoryDefinition?.recordset[0]?.definition) lines.push(`- Definition summary: ${inventoryDefinition.recordset[0].definition.replace(/\s+/g, ' ').slice(0, 600)}`, '');

  const materialColumns = byObject('MAS_KATALOG_SALES').concat(byObject('MAS_MATERIAL')).concat(byObject('PURC_MATCATALOG'));
  lines.push('## Sales-to-Material Bridge', '', `- MAS_KATALOG_SALES columns: ${byObject('MAS_KATALOG_SALES').map((column) => column.columnName).join(', ')}`, `- Material master candidates: ${['MAS_MATERIAL', 'PURC_MATCATALOG'].map((name) => `${name}: ${byObject(name).length ? byObject(name).map((column) => column.columnName).join(', ') : 'not found'}`).join('; ')}`);
  const bridge = await pool.request().query<Record<string, unknown>>(`SELECT TOP (20) k.Id,k.Nomor,k.MATERIALIDHED,pm.Materialid AS purcMaterialId,pm.MaterialName FROM dbo.MAS_KATALOG_SALES k LEFT JOIN dbo.PURC_MATCATALOG pm ON CONVERT(varchar(100),pm.Materialid)=CONVERT(varchar(100),k.MATERIALIDHED) WHERE NULLIF(LTRIM(RTRIM(k.MATERIALIDHED)),'') IS NOT NULL`);
  lines.push(`- Non-empty MATERIALIDHED samples: ${bridge.recordset.length}`, `- Direct MATERIALIDHED -> PURC_MATCATALOG.Materialid matches in bounded sample: ${bridge.recordset.filter((row) => row.purcMaterialId !== null).length}`, '- Status: PROBABLE only until key format and business meaning are validated.', '');

  const partBridge = await pool.request().query<{ salesParts: number; castingMatches: number; wmsProductMatches: number; wmsMaterialMatches: number; prProductMatches: number; prMaterialMatches: number }>(`WITH parts AS (SELECT DISTINCT TOP (50) d.PartNumber,d.ProductID FROM dbo.SLS_SALESORDER_NEW d WHERE NULLIF(LTRIM(RTRIM(d.PartNumber)),'') IS NOT NULL ORDER BY d.PartNumber) SELECT (SELECT COUNT(*) FROM parts) AS salesParts,(SELECT COUNT(*) FROM parts p JOIN dbo.casting1 c ON c.PART_NUMBER=p.PartNumber) AS castingMatches,(SELECT COUNT(*) FROM parts p JOIN dbo.WMS_MAPPING_PART_DELIVERY_PRD w ON CONVERT(varchar(100),w.ProductId)=p.ProductID) AS wmsProductMatches,(SELECT COUNT(*) FROM parts p JOIN dbo.WMS_MAPPING_PART_DELIVERY_PRD w ON CONVERT(varchar(100),w.MaterialIdRaw)=p.PartNumber OR CONVERT(varchar(100),w.MaterialIdSub)=p.PartNumber) AS wmsMaterialMatches,(SELECT COUNT(*) FROM parts p JOIN dbo.PRDetail r ON CONVERT(varchar(100),r.ProductID)=p.ProductID) AS prProductMatches,(SELECT COUNT(*) FROM parts p JOIN dbo.PRDetail r ON CONVERT(varchar(100),r.MaterialID)=p.PartNumber) AS prMaterialMatches`);
  lines.push('## Sales Part to Production/Material Bridge', '', `- Sampled Sales parts: ${partBridge.recordset[0]?.salesParts ?? 0}`, `- Exact casting1.PART_NUMBER matches: ${partBridge.recordset[0]?.castingMatches ?? 0}`, `- WMS mapping ProductId matches: ${partBridge.recordset[0]?.wmsProductMatches ?? 0}`, `- WMS mapping material-field matches: ${partBridge.recordset[0]?.wmsMaterialMatches ?? 0}`, `- PRDetail ProductID matches: ${partBridge.recordset[0]?.prProductMatches ?? 0}`, `- PRDetail MaterialID matches: ${partBridge.recordset[0]?.prMaterialMatches ?? 0}`, '- These are bridge candidates only; no production formula is enabled.', '');

  const productionObjects = [...new Set(columns.filter((column) => productionPattern.test(column.objectName)).map((column) => column.objectName))];
  lines.push('## Production-Like Objects', '');
  for (const objectName of productionObjects) {
    const objectMeta = byObject(objectName); const typeResult = await pool.request().input('name', sql.NVarChar, objectName).query<{ objectType: string }>(`SELECT CASE WHEN type='V' THEN 'VIEW' WHEN type='U' THEN 'TABLE' ELSE type END AS objectType FROM sys.objects WHERE schema_id=SCHEMA_ID('dbo') AND name=@name`); let rows = 0; try { const count = await pool.request().query<{ rows: number }>(`SELECT COUNT_BIG(*) AS rows FROM dbo.${q(objectName)}`); rows = Number(count.recordset[0]?.rows ?? 0); } catch { rows = 0; } lines.push(`- ${objectName} (${typeResult.recordset[0]?.objectType ?? 'unknown'}): ${rows} rows; domain columns: ${objectMeta.filter((column) => domainColumn.test(column.columnName)).map((column) => column.columnName).join(', ') || 'none'}`);
  }
  lines.push('', '## Conclusion', '', '- Sales Customer -> Header -> Detail -> Product: candidate for CONFIRMED_BY_DATA after this bounded validation is reviewed.', '- Sales -> Delivery: not confirmed without business-key match evidence.', '- Inventory quantity: UNKNOWN.', '- Production actual source and bridge: BLOCKED pending populated object and exact identifier match.', '');
  await mkdir(new URL('../../docs/', import.meta.url), { recursive: true });
  await writeFile(new URL('../../docs/business-link-validation.md', import.meta.url), lines.join('\n'), 'utf8');
  console.log(lines.join('\n'));
} finally { await closeSqlServer(); }
