import { getSqlServerPool } from '../config/sqlserver.js';
import sql from 'mssql';
import { compilePlan } from './compiler.js';
import { resolvePlan } from './resolver.js';
import type { SemanticPlan } from './schema.js';
export type SemanticRuntimeStage = 'semantic_plan' | 'resolver' | 'policy' | 'sql_compile' | 'db_connection' | 'sql_execution' | 'presenter';
export class SemanticRuntimeError extends Error {
  constructor(public readonly stage: SemanticRuntimeStage, public readonly errorCode: string, public readonly details: { sqlErrorNumber?: number; entity?: string } = {}, cause?: unknown) { super(`Semantic runtime failed at ${stage}: ${errorCode}`, { cause }); this.name = 'SemanticRuntimeError'; }
}
function safeErrorCode(error: unknown) { const value = error as { code?: unknown; name?: unknown }; return typeof value.code === 'string' ? value.code : typeof value.name === 'string' ? value.name : 'RUNTIME_ERROR'; }
function diagnostic(requestId: string | undefined, stage: SemanticRuntimeStage, status: 'START' | 'PASS' | 'FAIL', details: Record<string, unknown> = {}) { console.info(JSON.stringify({ event: 'SEMANTIC_RUNTIME_STAGE', requestId, stage, status, ...details })); }
export async function executeSemanticPlan(plan: SemanticPlan, requestId?: string) {
  if (plan.entity === 'material_requirement' && (plan.select.includes('pr_creation_status') || plan.filters.some((filter) => filter.field === 'pr_creation_status'))) return executeLifecyclePlan(plan, requestId);
  const entity = plan.entity;
  diagnostic(requestId, 'resolver', 'START', { entity });
  let resolved;
  try { resolved = resolvePlan(plan); } catch (error) { const wrapped = error instanceof SemanticRuntimeError ? error : new SemanticRuntimeError('resolver', safeErrorCode(error), { entity }, error); diagnostic(requestId, 'resolver', 'FAIL', { entity, errorCode: wrapped.errorCode }); throw wrapped; }
  const resolvedFields = [...resolved.fields.entries()].map(([name, field]) => ({ name, physicalObject: field.physicalObject, physicalColumn: field.physicalColumn, confidence: field.confidence }));
  diagnostic(requestId, 'resolver', 'PASS', { entity: resolved.entity.entity, physicalSource: resolved.entity.baseObject, resolvedFields, joinRequired: resolvedFields.some((field) => field.physicalObject !== resolved.entity.baseObject) });
  diagnostic(requestId, 'sql_compile', 'START', { entity: resolved.entity.entity });
  let compiled;
  try { compiled = compilePlan(resolved); } catch (error) { const wrapped = new SemanticRuntimeError('sql_compile', safeErrorCode(error), { entity }, error); diagnostic(requestId, 'sql_compile', 'FAIL', { entity, errorCode: wrapped.errorCode }); throw wrapped; }
  diagnostic(requestId, 'sql_compile', 'PASS', { entity: resolved.entity.entity, compiled: true });
  diagnostic(requestId, 'db_connection', 'START', { entity: resolved.entity.entity });
  let pool;
  try { pool = await getSqlServerPool(); } catch (error) { const wrapped = new SemanticRuntimeError('db_connection', safeErrorCode(error), { entity }, error); diagnostic(requestId, 'db_connection', 'FAIL', { entity, errorCode: wrapped.errorCode }); throw wrapped; }
  diagnostic(requestId, 'db_connection', 'PASS', { entity: resolved.entity.entity });
  diagnostic(requestId, 'sql_execution', 'START', { entity: resolved.entity.entity });
  try { const request = pool.request(); for (const parameter of compiled.params) request.input(parameter.name, parameter.type, parameter.value); const result = await request.query(compiled.text); const columns = plan.aggregates.length ? [...plan.groupBy, ...plan.aggregates.map((aggregate) => aggregate.as)] : plan.metrics.length ? plan.metrics.map((_, index) => `metric${index}`) : plan.select; const rows = result.recordset.map((row) => Object.fromEntries(columns.map((name) => [name, row[name] ?? row[resolved.fields.get(name)?.physicalColumn ?? name]]))); diagnostic(requestId, 'sql_execution', 'PASS', { entity: resolved.entity.entity, rowCount: rows.length }); return { entity: resolved.entity.entity, rows, rowCount: rows.length, columns, returnedCount: rows.length, limit: plan.limit, offset: plan.offset, hasMore: rows.length === plan.limit }; } catch (error) { const value = error as { number?: unknown; code?: unknown; name?: unknown }; const sqlErrorNumber = typeof value.number === 'number' ? value.number : undefined; const wrapped = new SemanticRuntimeError('sql_execution', typeof value.code === 'string' ? value.code : typeof value.name === 'string' ? value.name : 'SQL_EXECUTION_ERROR', { entity, ...(sqlErrorNumber === undefined ? {} : { sqlErrorNumber }) }, error); diagnostic(requestId, 'sql_execution', 'FAIL', { entity, errorCode: wrapped.errorCode, ...(sqlErrorNumber === undefined ? {} : { sqlErrorNumber }) }); throw wrapped; }
}
async function executeLifecyclePlan(plan: SemanticPlan, requestId?: string) {
  const pool = await getSqlServerPool(); const params: Array<{ name: string; value: unknown; type: sql.ISqlType | sql.ISqlTypeFactoryWithNoParams }> = []; const where: string[] = [];
  for (const filter of plan.filters) { if (filter.field === 'material_description' && filter.operator === 'contains_all' && Array.isArray(filter.value)) { filter.value.forEach((value, index) => { const name = `material${index}`; params.push({ name, value: `%${String(value)}%`, type: sql.NVarChar(255) }); where.push(`material.MaterialName LIKE @${name}`); }); } if (filter.field === 'pr_creation_status' && filter.operator === 'eq' && typeof filter.value === 'string') { params.push({ name: 'status', value: filter.value, type: sql.NVarChar(30) }); where.push(`lifecycle.pr_creation_status = @status`); } }
  const lifecycleWhere = [`lifecycle.pr_creation_status <> 'DATA_MAPPING_EXCEPTION'`, ...where];
  const query = `WITH mrp_material AS (SELECT DISTINCT m.MRPNo,m.MaterialId FROM dbo.PURCH_MRP m WHERE NULLIF(LTRIM(RTRIM(m.MRPNo)),'') IS NOT NULL AND m.MaterialId IS NOT NULL), MRP_PR_BRIDGE AS (SELECT DISTINCT t.MRPNo,t.MaterialId,t.PRNo FROM dbo.PURC_PURCHREQUEST_TEMP t WHERE NULLIF(LTRIM(RTRIM(t.MRPNo)),'') IS NOT NULL AND t.MaterialId IS NOT NULL AND NULLIF(LTRIM(RTRIM(t.PRNo)),'') IS NOT NULL), final_pr AS (SELECT DISTINCT f.PRNo,f.MaterialId FROM dbo.PURC_PURCHASE_REQUEST f WHERE NULLIF(LTRIM(RTRIM(f.PRNo)),'') IS NOT NULL AND f.MaterialId IS NOT NULL), counts AS (SELECT g.MRPNo,g.MaterialId,COUNT(DISTINCT b.PRNo) AS released_pr_count,COUNT(DISTINCT CASE WHEN f.PRNo IS NOT NULL THEN b.PRNo END) AS final_pr_count FROM mrp_material g LEFT JOIN MRP_PR_BRIDGE b ON b.MRPNo=g.MRPNo AND b.MaterialId=g.MaterialId LEFT JOIN final_pr f ON f.PRNo=b.PRNo AND f.MaterialId=b.MaterialId GROUP BY g.MRPNo,g.MaterialId), lifecycle AS (SELECT MRPNo,MaterialId,CASE WHEN final_pr_count > released_pr_count THEN 'DATA_MAPPING_EXCEPTION' WHEN released_pr_count=0 OR final_pr_count=0 THEN 'BELUM_DIBUAT_PR' WHEN final_pr_count<released_pr_count THEN 'SEBAGIAN_DIBUAT_PR' ELSE 'SUDAH_DIBUAT_PR' END AS pr_creation_status FROM counts), material AS (SELECT lifecycle.MRPNo,lifecycle.MaterialId,mc.MaterialName FROM lifecycle LEFT JOIN dbo.PURC_MATCATALOG mc ON mc.Materialid=lifecycle.MaterialId) SELECT ${plan.offset > 0 ? '' : 'TOP (@limit) '} material.MRPNo AS mrp_number,material.MaterialId AS material_code,material.MaterialName AS material_description,lifecycle.pr_creation_status FROM lifecycle JOIN material ON material.MRPNo=lifecycle.MRPNo AND material.MaterialId=lifecycle.MaterialId WHERE ${lifecycleWhere.join(' AND ')} ORDER BY material.MRPNo,material.MaterialId${plan.offset > 0 ? ' OFFSET @offset ROWS FETCH NEXT @limit ROWS ONLY' : ''}`;
  const request = pool.request().input('limit', sql.Int, Math.min(plan.limit, 500)); if (plan.offset > 0) request.input('offset', sql.Int, plan.offset); for (const parameter of params) request.input(parameter.name, parameter.type, parameter.value); const result = await request.query(query); const columns = ['mrp_number', 'material_code', 'material_description', 'pr_creation_status']; diagnostic(requestId, 'sql_execution', 'PASS', { entity: 'material_requirement', rowCount: result.recordset.length, lifecycle: true }); return { entity: 'material_requirement', rows: result.recordset, rowCount: result.recordset.length, columns, returnedCount: result.recordset.length, limit: plan.limit, offset: plan.offset, hasMore: result.recordset.length === plan.limit };
}
