export const TYPE_GROUPS = {
  NUMERIC: new Set(['tinyint', 'smallint', 'int', 'bigint', 'decimal', 'numeric', 'money', 'smallmoney', 'float', 'real']),
  BOOLEAN: new Set(['bit']), DATE_TIME: new Set(['date', 'datetime', 'datetime2', 'smalldatetime', 'datetimeoffset']), TIME_ONLY: new Set(['time']), STRING: new Set(['char', 'varchar', 'nchar', 'nvarchar']),
  LEGACY_TEXT: new Set(['text', 'ntext']), IDENTIFIER: new Set(['uniqueidentifier']), BINARY: new Set(['binary', 'varbinary', 'image', 'timestamp', 'rowversion'])
} as const;
export function normalizeType(datatype: string) { return datatype.trim().toLowerCase(); }
export function quoteIdentifier(value: string) { if (!value || /[\u0000-\u001f]/.test(value)) throw new Error('Invalid metadata identifier rejected.'); return `[${value.replace(/]/g, ']]')}]`; }
export function profilePlan(datatype: string, objectName: string, columnName: string) { const type = normalizeType(datatype); const [schema, object] = objectName.split('.'); const qualified = `${quoteIdentifier(schema)}.${quoteIdentifier(object)}`; const column = quoteIdentifier(columnName); if (TYPE_GROUPS.NUMERIC.has(type)) return { group: 'NUMERIC', status: 'PROFILED', text: `SELECT COUNT_BIG(*) AS rowEstimate,SUM(CASE WHEN ${column} IS NULL THEN 1 ELSE 0 END) AS nullCount,COUNT(DISTINCT ${column}) AS distinctCount,MIN(${column}) AS minNumeric,MAX(${column}) AS maxNumeric FROM ${qualified}` }; if (TYPE_GROUPS.BOOLEAN.has(type)) return { group: 'BOOLEAN', status: 'PROFILED', text: `SELECT COUNT_BIG(*) AS rowEstimate,SUM(CASE WHEN ${column} IS NULL THEN 1 ELSE 0 END) AS nullCount,COUNT(DISTINCT CONVERT(int,${column})) AS distinctCount FROM ${qualified}` }; if (TYPE_GROUPS.DATE_TIME.has(type)) return { group: 'DATE_TIME', status: 'PROFILED', text: `SELECT COUNT_BIG(*) AS rowEstimate,SUM(CASE WHEN ${column} IS NULL THEN 1 ELSE 0 END) AS nullCount,MIN(${column}) AS minDate,MAX(${column}) AS maxDate FROM ${qualified}` }; if (TYPE_GROUPS.TIME_ONLY.has(type)) return { group: 'TIME_ONLY', status: 'PROFILED', text: `SELECT COUNT_BIG(*) AS rowEstimate,SUM(CASE WHEN ${column} IS NULL THEN 1 ELSE 0 END) AS nullCount,MIN(${column}) AS minTime,MAX(${column}) AS maxTime FROM ${qualified}` }; if (TYPE_GROUPS.STRING.has(type)) return { group: 'STRING', status: 'PROFILED', text: `SELECT COUNT_BIG(*) AS rowEstimate,SUM(CASE WHEN ${column} IS NULL THEN 1 ELSE 0 END) AS nullCount,COUNT(DISTINCT ${column}) AS distinctCount,MIN(LEN(${column})) AS minLength,MAX(LEN(${column})) AS maxLength,AVG(CONVERT(float,LEN(${column}))) AS averageLength FROM ${qualified}` }; if (TYPE_GROUPS.IDENTIFIER.has(type)) return { group: 'IDENTIFIER', status: 'PROFILED', text: `SELECT COUNT_BIG(*) AS rowEstimate,SUM(CASE WHEN ${column} IS NULL THEN 1 ELSE 0 END) AS nullCount,COUNT(DISTINCT ${column}) AS distinctCount FROM ${qualified}` }; return { group: 'OTHER', status: 'SKIPPED_UNSUPPORTED_TYPE' };
}
