import sql from 'mssql';
import { getSqlServerPool } from '../config/sqlserver.js';
import { env } from '../config/env.js';

type DeliveryRow = { deliveryId: number; deliveryNumber: string | null; customerCode: string; customerName: string | null; customerPoNumber: string | null; deliveryDate: string | null; salesNumber: string | null; productId: string | null; partNumber: string | null; quantity: number | null; status: string | null };

export class DeliveryRepository {
  async getCustomerDeliveries(customerCode: string, dateFrom?: string, dateTo?: string) {
    const pool = await getSqlServerPool(); const request = pool.request(); request.input('limit', sql.Int, env.DB_MAX_ROWS); request.input('customerCode', sql.VarChar(50), customerCode); let filter = ' WHERE CONVERT(varchar(50), h.CustomerID) = @customerCode'; if (dateFrom && dateTo) { request.input('dateFrom', sql.Date, dateFrom); request.input('dateTo', sql.Date, dateTo); filter += ' AND h.Tanggal >= @dateFrom AND h.Tanggal < DATEADD(day, 1, @dateTo)'; } const result = await request.query<DeliveryRow>(`SELECT TOP (@limit) h.Id AS deliveryId, h.Nomor AS deliveryNumber, CONVERT(varchar(50), h.CustomerID) AS customerCode, c.CustomerName AS customerName, h.PONo AS customerPoNumber, h.Tanggal AS deliveryDate, d.SalesNomor AS salesNumber, d.ProductID AS productId, CAST(NULL AS nvarchar(255)) AS partNumber, d.Qty AS quantity, h.status FROM dbo.SLS_DELIVERYORDER_HED_NEW h LEFT JOIN dbo.SLS_DELIVERYORDER_NEW d ON d.HedId = h.Id LEFT JOIN dbo.MAS_CUSTOMER c ON c.CustId = h.CustomerID${filter} ORDER BY h.Tanggal DESC, h.Id DESC, d.Id`); return result.recordset;
  }
  async getDeliveryByNumber(deliveryNo: string) { const pool = await getSqlServerPool(); const request = pool.request(); request.input('limit', sql.Int, env.DB_MAX_ROWS); request.input('deliveryNo', sql.NVarChar(100), deliveryNo.trim()); const result = await request.query<DeliveryRow>(`SELECT TOP (@limit) h.Id AS deliveryId, h.Nomor AS deliveryNumber, CONVERT(varchar(50), h.CustomerID) AS customerCode, c.CustomerName AS customerName, h.PONo AS customerPoNumber, h.Tanggal AS deliveryDate, d.SalesNomor AS salesNumber, d.ProductID AS productId, CAST(NULL AS nvarchar(255)) AS partNumber, d.Qty AS quantity, h.status FROM dbo.SLS_DELIVERYORDER_HED_NEW h LEFT JOIN dbo.SLS_DELIVERYORDER_NEW d ON d.HedId = h.Id LEFT JOIN dbo.MAS_CUSTOMER c ON c.CustId = h.CustomerID WHERE h.Nomor = @deliveryNo OR h.PONo = @deliveryNo OR d.SalesNomor = @deliveryNo OR d.NoPO = @deliveryNo ORDER BY h.Tanggal DESC, h.Id DESC, d.Id`); return result.recordset; }
}
